export const makes = [
  {
    label: "Abarth",
    value: "Abarth",
    models: [
      "124 GT",
      "124 Spider",
      "500C",
      "595",
      "595 Competizione",
      "595 Esseesse",
      "595 Pista",
      "595 Turismo",
      "695",
      "695 Biposto",
      "Punto",
      "Tributo Ferrari",
    ],
  },

  {
    label: "Alfa Romeo",
    value: "Alfa Romeo",
    models: [
      "147",
      "156",
      "159",
      "164",
      "2000",
      "33",
      "33 Stradale",
      "4C",
      "75",
      "90",
      "Alfasud",
      "Alfetta",
      "Brera",
      "Duetto",
      "Giulia",
      "Giulia Quadrifoglio",
      "Giulietta",
      "GTV",
      "MiTo",
      "Montreal",
      "Spider",
      "Stelvio",
      "Stelvio Quadrifoglio",
      "SZ",
    ],
  },
  {
    label: "Aston Martin",
    value: "Aston Martin",
    models: [
      "Cygnet",
      "DB10",
      "DB11",
      "DBR1",
      "DBS Superleggera",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Valhalla",
      "Vantage",
      "Victor",
    ],
  },
  {
    label: "Audi",
    value: "Audi",
    models: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "e-tron",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "R8",
      "RS3",
      "RS5",
      " RS7",
      "TT",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    models: ["Model 11", "Model 12", "Model 13", "Model 14"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    models: [
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
    ],
  },
  {
    label: "Bentley",
    value: "Bentley",
    models: [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental GT",
      "Flying Spur",
      "Mulsanne",
      "R-Type",
      "S1",
      "S2",
      "Speed Six",
      "T-Series",
    ],
  },
  {
    label: "Bestune",
    value: "Bestune",
    models: [
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
    ],
  },
  {
    label: "BMW",
    value: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "E46 M3",
      "i Series",
      "Series 7",
      "X Series",
      "Z Series",
    ],
  },
  {
    label: "Bugatti",
    value: "Bugatti",
    models: [
      "Bolide",
      "Centodieci",
      "Chiron",
      "Chiron Pur Sport",
      "Chiron Super Sport",
      "Divo",
      "EB110",
      "La Finale",
      "La Voiture Noire",
      "Type 251",
      "Type 35",
      "Type 57",
      "Veyron",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    models: [
      "Dolphin",
      "E3",
      "e6",
      "FO",
      "G3",
      "Han",
      "L3",
      "Qin",
      "S3",
      "Seal",
      "Song",
      "T3",
      "Tang",
      "Yuan",
    ],
  },
  {
    label: "Cadillac",
    value: "Cadillac",
    models: ["CT4", "CT5", "CT6", "Escalade", "Lyriq", "CT4", "CT5", "CT6"],
  },
  {
    label: "Changan",
    value: "Changan",
    models: [
      "Alsvin",
      "Benni",
      "CS15",
      "CS35",
      "CS55",
      "CS75",
      "Eado",
      "Hunter",
      "Kaicene",
      "Oushang",
      "Raeton",
      "Star 5",
      "Uni-K",
      "Uni-T",
    ],
  },
  {
    label: "Chery",
    value: "Chery",
    models: [
      "Arrizo",
      "Eastar",
      "Exeed",
      "Fulwin",
      "Karry",
      "QQ",
      "Tiggo",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
    ],
  },
  {
    label: "Chevrolet",
    value: "Chevrolet",
    models: [
      "Avalanche",
      "Blazer",
      "Camaro",
      "Caprice",
      "Chevelle",
      "Corvette",
      "Equinox",
      "Impala",
      "Malibu",
      "Monte Carlo",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "Tahoe",
      "Traverse",
      "Trax",
      "Volt",
    ],
  },
  {
    label: "Chrysler",
    value: "Chrysler",
    models: [
      "200",
      "300",
      "300C",
      "300M",
      "Aspen",
      "Cirrus",
      "Concorde",
      "Cordoba",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Pacifica",
      "Prowler",
      "PT Cruiser",
      "Sebring",
      "Voyager",
    ],
  },
  {
    label: "Citroen",
    value: "Citroen",
    models: [
      "Ami",
      "Berlingo",
      "C-Elysee",
      "C3",
      "C4",
      "C5",
      "C5 X",
      "C6",
      "Dispatch",
      "DS 3",
      "DS 4",
      "DS 7",
      "Jumpy",
      "Picasso",
      "Spacetourer",
    ],
  },
  { label: "CMC", value: "CMC", models: ["Veryca"] },
  {
    label: "Dodge",
    value: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Challenger SRT Hellca",
      "Charger",
      "Dakota",
      "Dart",
      "Durango",
      "Durango RT",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stratus",
      "Viper",
    ],
  },
  {
    label: "DongFeng",
    value: "DongFeng",
    models: [
      "A9",
      "AX3",
      "AX5",
      "AX7",
      "Dingo",
      "F12",
      "F5",
      "Fengon",
      "Joyear",
      "K10",
      "M5",
      "Rich",
      "Sokon",
      "V3",
      "Warrior",
    ],
  },
  {
    label: "Exeed",
    value: "Exeed",
    models: ["EOL", "EOL Pro", "GL6", "LSE", "LX", "VX", "VX Plus"],
  },

  {
    label: "Fengon",
    value: "Fengon",
    models: [
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
    ],
  },
  {
    label: "Ferrari",
    value: "Ferrari",
    models: [
      "348",
      "488 Pista",
      "488 Spider",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "Daytona SP3",
      "Dino",
      "F12 Berlinetta",
      "F12 TDF",
      "F8 Spider",
      "F8 Tributo",
      "GTC4Lusso",
      "LaFerrari",
      "LaFerrari Aperta",
      "Monza SP1",
      "Monza SP2",
      "P80/C",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "SP3",
      "Superfast",
    ],
  },

  {
    label: "Fiat",
    value: "Fiat",
    models: [
      "500",
      "500L",
      "500X",
      "Ducato",
      "Panda",
      "Scudo",
      "Talento",
      "Tipo",
    ],
  },
  {
    label: "Ford",
    value: "Ford",
    models: [
      "Bronco",
      "Bronco Sport",
      "C-Max",
      "Edge",
      "Edge Sport",
      "Escape",
      "Everest Hybrid",
      "Explorer",
      "F-150",
      "F-150 Raptor",
      "F-250",
      "F-350",
      "Focus",
      "Fusion",
      "Grand C-Max",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Ranger",
      "Taunus",
      "Taurus",
    ],
  },
  {
    label: "Forthing",
    value: "Forthing",
    models: [
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
    ],
  },
  {
    label: "Foton",
    value: "Foton",
    models: [
      "Aumark",
      "Forland",
      "G9",
      "Gratour",
      "Ollin",
      "Sauvana",
      "Transits",
      "Tunland",
      "View",
      "Weichai",
    ],
  },
  {
    label: "GAC",
    value: "GAC",
    models: [
      "Aion LX",
      "Aion S",
      "Aion V",
      "Arkana",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "Haval F5",
      "Haval F7",
      "Haval H6",
      "Haval H9",
      "Trumpchi GA6",
      "Trumpchi GA8",
      "Trumpchi GS5",
      "Trumpchi M6",
      "ZHONGYI",
    ],
  },
  {
    label: "Geely",
    value: "Geely",
    models: [
      "Aion",
      "Haifeng",
      "Haijie",
      "Jiaji EV",
      "KX3",
      "Lykov EV",
      "Meizu ES6",
      "Meizu ES6 Plus",
      "Meizu EVO",
      "Pionner",
      "Pionner Plus",
      "Vision X50",
      "Xing Rui",
      "Xingyue",
      "Xingyue L",
    ],
  },
  {
    label: "Genesis",
    value: "Genesis",
    models: [
      "Electrified G80",
      "Electrified GV70",
      "G70",
      "G80",
      "G90",
      "GV70",
      "GV80",
    ],
  },
  {
    label: "GMC",
    value: "GMC",
    models: [
      "Acadia",
      "Canyon",
      "Encanto",
      "Envoy",
      "Envoy SLT",
      "Envoy XUV",
      "HUMMER H2",
      "Savana",
      "Sierra",
      "Terrain",
    ],
  },
  {
    label: "Great Wall",
    value: "Great Wall",
    models: [
      "Coolbear",
      "Heimao",
      "Pao",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 7",
    ],
  },
  {
    label: "Haval",
    value: "Haval",
    models: [
      "CUV H",
      "F7 Plus",
      "F7x",
      "H2",
      "H6",
      "H7",
      "H9",
      "H9 LUX",
      "Jolion",
      "Jolion Hybrid",
      "M6",
    ],
  },
  {
    label: "Hino",
    value: "Hino",
    models: ["Hino 300", "Hino 500", "Hino 600", "Hino Dutro"],
  },
  { label: "HiPhi", value: "HiPhi", models: ["HiPhi X", "HiPhi Y", "HiPhi Z"] },
  {
    label: "Honda",
    value: "Honda",
    models: [
      "Accord",
      "Civic",
      "Civic Si",
      "Civic Type R",
      "Clarity",
      "CR-V",
      "Fit",
      "Insight",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    models: ["E-HS9", "E-QM5", "H5", "H9L", "HS3", "HS5", "HS7", "L5"],
  },
  {
    label: "Hyundai",
    value: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Genesis",
      "Ioniq",
      "Kona",
      "Nexo",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Sonata",
      "Tucson",
      "Veloster",
    ],
  },
  { label: "INEOS", value: "INEOS", models: ["Grenadier"] },
  {
    label: "Infiniti",
    value: "Infiniti",
    models: [
      "Q50",
      "Q60",
      "Q70",
      "Q80",
      "QX30",
      "QX50",
      "QX55",
      "QX60",
      "QX80",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    models: [
      "Amigo",
      "Ascender",
      "D-Max",
      "Elf",
      "F-Series",
      "Impulse",
      "MU-X",
      "N-Series",
      "NPR",
      "P'up",
      "Rodeo",
      "Trooper",
    ],
  },
  {
    label: "Jac",
    value: "Jac",
    models: [
      "J4",
      "J6",
      "J7",
      "Refine S3",
      "Refine S5",
      "S2",
      "S3",
      "S5",
      "S7",
      "T6",
      "T8",
    ],
  },
  {
    label: "Jaguar",
    value: "Jaguar",
    models: [
      "E-Pace",
      "E-Pace R-Dynamic",
      "F-PACE",
      "F-PACE SVR",
      "F-TYPE",
      "F-TYPE R",
      "F-TYPE S",
      "F-TYPE SVR",
      "I-PACE",
      "I-PACE HSE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XF Sportbrake",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK F-TYPE R",
      "XKR",
    ],
  },
  {
    label: "Jeep",
    value: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "Jetour",
    value: "Jetour",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "JMC",
    value: "JMC",
    models: [
      "Baoda",
      "Carrying",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "Landwind",
      "Teshun",
      "Vigus",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    models: ["E5", "EQ1", "K1", "K2", "K3", "K6", "K7", "S3", "S5", "S7", "S9"],
  },
  {
    label: "Kia",
    value: "Kia",
    models: [
      "Forte",
      "Niro",
      "Optima",
      "Rio",
      "Rondo",
      "Sedona",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
    ],
  },
  {
    label: "Koenigsegg",
    value: "Koenigsegg",
    models: [
      "Agera",
      "CC8S",
      "CCR",
      "CCX",
      "CCX-R",
      "Gemera",
      "Jesko",
      "One:1",
      "Quattroporte",
      "Regera",
    ],
  },
  {
    label: "Lamborghini",
    value: "Lamborghini",
    models: [
      "Asterion",
      "Aventador",
      "Aventador S",
      "Centenario",
      "Countach",
      "Estoque",
      "Gallardo",
      "Gallardo Spyder",
      "Huracan",
      "Huracán",
      "Huracán EVO",
      "Huracán Spyder",
      "Murciélago",
      "Reventón",
      "Sián",
      "Urus",
      "Urus Performante",
    ],
  },
  {
    label: "Land Rover",
    value: "Land Rover",
    models: [
      "Range Rover",
      "Defender",
      "Discovery",
      "Dicovery Sport",
      "Range Rover Sport",
    ],
  },
  {
    label: "Lexus",
    value: "Lexus",
    models: [
      "ES",
      "GS",
      "IS",
      "LC 500",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "UX",
    ],
  },
  {
    label: "Lotus",
    value: "Lotus",
    models: [
      "Carlton",
      "Eclat",
      "Elan",
      "Elise",
      "Elite",
      "Esprit",
      "Europa",
      "Evora",
      "Exige",
      "Seven",
    ],
  },
  { label: "Lucid", value: "Lucid", models: ["Air", "Gravity"] },
  {
    label: "Mahindra",
    value: "Mahindra",
    models: [
      "Alturas G4",
      "Bolero",
      "eKUV100",
      "Furio",
      "KUV100",
      "Marazzo",
      "Pick Up",
      "Scorpio",
      "Scorpio-N",
      "Thar",
      "TUV300",
      "XUV300",
      "XUV700",
      "Xylo",
    ],
  },
  {
    label: "Maserati",
    value: "Maserati",
    models: [
      "Alfieri",
      "Biturbo",
      "Ghibli",
      "GranCabrio",
      "Granturismo",
      "Levante",
      "MC20",
      "Quattroporte",
      "Shamal",
    ],
  },
  {
    label: "Mazda",
    value: "Mazda",
    models: [
      "Mazda CX-3",
      "Mazda CX-30",
      "Mazda CX-5",
      "Mazda CX-50",
      "Mazda CX-9",
      "Mazda MX-5 Miata",
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "MX-5 Miata",
    ],
  },
  {
    label: "McLaren",
    value: "McLaren",
    models: [
      "12C Spider",
      "540C",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "GTR",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
    ],
  },
  {
    label: "Mercedes-Benz",
    value: "Mercedes-Benz",
    models: [
      "A 200",
      "A-Class",
      "AMG CLA-Class",
      "AMG GT",
      "AMG GT Roadster",
      "B-Class",
      "C-Class",
      "CLA",
      "Class S",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQS",
      "G-Class",
      "GLA",
      "GLC",
      "GLC300",
      "GLC350e 4MATIC",
      "GLE",
      "GLS",
      "S-Class",
      "SL",
      "Sprinter",
      "V-Class",
      "X-Class",
    ],
  },
  {
    label: "Mitsubishi",
    value: "Mitsubishi",
    models: [
      "3000GT",
      "ASX",
      "Carisma",
      "Colt",
      "Eclipse",
      "Galant",
      "i-MiEV",
      "Lancer",
      "Montero",
      "Outlander",
      "Pajero",
      "RVR",
      "Shogun",
      "Xpander Cross",
    ],
  },
  {
    label: "Nissan",
    value: "Nissan",
    models: [
      "370Z",
      "370Z Nismo",
      "Altima",
      "Armada",
      "Frontier",
      "GT-R",
      "Juke",
      "Maxima",
      "Murano",
      "Pathfinder",
      "Rogue",
      "Sentra",
      "Titan",
      "Versa",
    ],
  },
  { label: "Peugeot", value: "Peugeot", models: ["3008", "5008"] },
  { label: "Porsche", value: "Porsche", models: ["911", "Cayenne", "Macan"] },
  { label: "RAM", value: "RAM", models: ["1500", "2500"] },
  {
    label: "Renault",
    value: "Renault",
    models: ["Grand Scenic", "Megane", "Talisman"],
  },
  {
    label: "Rolls-Royce",
    value: "Rolls-Royce",
    models: [
      "Corniche",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Spectre",
      "Wraith",
    ],
  },
  {
    label: "Skoda",
    value: "Skoda",
    models: [
      "Citigo-e iV",
      "Enyaq iV",
      "Fabia",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  {
    label: "Tesla",
    value: "Tesla",
    models: ["Model S", "Model 3", "Model X", "Model Y"],
  },
  {
    label: "Toyota",
    value: "Toyota",
    models: ["Corolla", "Camry", "RAV4 Adventure", "Supra 191 Edition"],
  },
  {
    label: "Volkswagen",
    value: "Volkswagen",
    models: [
      "Beetle",
      "Bora",
      "Corrado",
      "EOS",
      "Eos CC",
      "Fox",
      "Golf",
      "Golf Estate",
      "Golf GTI",
      "Golf Hatchback",
      "Golf R",
      "Golf SV",
      "ID3",
      "Jetta",
      "Jetta GLI",
      "Passat",
      "Passat CC",
      "Passat Estate",
      "Phaeton",
      "Polo",
      "Rabbit",
      "RNS",
      "Scirocco",
      "Sharan",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  { label: "Volvo", value: "Volvo", models: ["XC90", "S60", "V60"] },
  { label: "Xiaomi", value: "Xiaomi", models: ["SU7"] },
  { label: "Zeekr", value: "Zeekr", models: ["001", "X"] },
];

export const arabicMakes = [
  {
    label: "أبارث",
    value: "أبارث",
    models: ["الكل", "124", "1999", "595", "695", "595 اف", "آخرى"],
  },

  {
    label: "ألفا روميو",
    value: "ألفا روميو",
    models: [
      "الكل",
      "145/146/147",
      "159/156",
      "166",
      " سي4",
      " سي8",
      "بريرا",
      "GIULIETTA",
      "GTV/GT",
      "Giulia",
      "Mito",
      "Spider",
      "Stelvio",
      "Tonale",
      "آخرى",
    ],
  },
  {
    label: " أستون مارتن ",
    value: " أستون مارتن ",
    models: [
      "الكل",
      "Cygnet",
      "DB10",
      "DB11",
      "DB12",
      "DB7",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Vanquish",
      "Vantage",
      "Virage",
      "Vulcan",
      "Zagato",
      "Other",
      "آخرى",
    ],
  },
  {
    label: "أودي ",
    value: "أودي ",
    models: [
      "الكل",
      "A1",
      "A2",
      "A3",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3 / S-Q3 / RS-Q3",
      " Q5 / S-Q5 / RS-Q5",
      " Q7 / S-Q7",
      " Q8 / S-Q8 / RS-Q8",
      " e-tron / RS e-tron",
      "S3/RS3",
      "S4/RS4",
      "S5/RS5",
      "S6/RS6",
      "S7/RS7",
      "S8",
      "R8",
      "TT",
      "e-tron / RS e-tron",
      "آخرى",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    models: ["الكل", "Model 11", "Model 12", "Model 13", "Model 14", "آخرى"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    models: [
      "الكل",
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
      "آخرى",
    ],
  },
  {
    label: "بنتلى ",
    value: "بنتلى ",
    models: [
      "الكل",
      " أرنـاج",
      "أزور",
      "بنتايغا",
      "بروك لاندز",
      "كونتينينتال",
      "كونتينينتال جي تي  ",
      "فلاينغ سبير",
      "مالسان",
      "آخرى",
    ],
  },
  {
    label: "بيستون ",
    value: "بيستون ",
    models: [
      "الكل",
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
      "آخرى",
    ],
  },
  {
    label: "بي ام دبليو ",
    value: "بي ام دبليو ",
    models: [
      "الكل",
      "1 الفئة",
      "2 الفئة",
      "3 الفئة",
      "4 الفئة",
      "5 الفئة",
      "6 الفئة",
      "7 الفئة",
      "8 الفئة",
      "i الفئة",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z1",
      "Z3",
      "Z4",
      "Z8",
      "آخرى",
    ],
  },
  {
    label: "بوغاتي ",
    value: "بوغاتي ",
    models: [
      "الكل",
      "بُلَيْد",
      "سنتوديتشي",
      "شيرون",
      "ديفو",
      "110 إي بي",
      " لا فينال",
      "لا فواتور نوار",
      " 251 تايب ",
      " 35تايب  ",
      " 57 تايب ",
      "فيرون",
      "آخرى",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    models: [
      "الكل",
      "ATTO 3",
      "Dolphin",
      "F3",
      "F5",
      "F6",
      "F7",
      "HAN",
      "Leopard",
      "Qin",
      "Seal",
      "Seagul",
      "Sealion",
      "Song",
      "Song L",
      "Song Plus",
      "Song Pro",
      "Tang",
      "Tengshi D9",
      "Yangwang U8",
      "Yuan Plus",
      "Yuan up",
      "E2",
      "آخرى",
    ],
  },
  {
    label: "كاديلاك",
    value: "كاديلاك",
    models: [
      "الكل",
      "ATS",
      "BLS",
      "CT4",
      "CT6",
      "CTS/Catera",
      "DTS/De Ville",
      "إسكاليد",
      "Fleetwood",
      "Lyriq",
      "SLS",
      "STS/Seville",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTR/Eldorado",
      "XTS",
      "آخرى",
    ],
  },
  {
    label: "شانجان ",
    value: "شانجان",
    models: [
      "الكل",
      "Alsvin",
      "Alsvin V7",
      "CS35",
      "CS35 Plus",
      "CS75",
      "CS75 Plus",
      "CS85",
      "CS95",
      "Deepai G318",
      "E Star",
      "Eado",
      "Eado Plus",
      "Lumin",
      "Starlight",
      "UNI-K",
      "Uni-T",
      "Uni-V",
      "آخرى",
    ],
  },
  {
    label: "شيري ",
    value: "شيري",
    models: [
      "الكل",
      "A11",
      "AIQAR",
      "Arrizo 3",
      "Arizzo 5",
      "Arizzo 7",
      "B11",
      "E5",
      "E8",
      "QQ",
      "S11",
      "Tiggo 3",
      "Tiggo 4",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
      "Tiggo 9",
      "V5",
      "iCar",
      "iCar 03",
      "آخرى",
    ],
  },
  {
    label: "شيفروليه",
    value: "شيفروليه",
    models: [
      "الكل",
      "افالانش",
      "أسترو",
      "أباتشي",
      "أفيو",
      "Bel Air",
      "بليزر",
      "بولت",
      "CSV",
      "كامارو",
      "كابريس",
      "كابتيفا",
      "كافالير",
      "شيفيل",
      "كولورادو",
      "كورفيت",
      "كروز",
      "ابيكا",
      "ايكونس",
      "اكسبلورر",
      "اكسبرس",
      "غرووف",
      "إمبالا",
      "لومينا",
      "ماليبو",
      "مونت كارلو",
      "نوفا",
      "أوبترا",
      "بيك اب",
      "SSR",
      "سيلفرادو",
      "سونيك",
      "سبارك",
      "سوبربان",
      "تاهو",
      "تريل بليزر",
      "ترافيرس",
      "تراكس",
      "أبلاندر",
      "آخرى",
    ],
  },
  {
    label: "كرايسلر",
    value: "كرايسلر",
    models: [
      "الكل",
      "200 / 200C EV",
      "300 / 300C / 300M",
      "Concorde",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Neon",
      "PT Cruiser",
      "Pacifica",
      "Prowler",
      "Sebring",
      "Voyager / Caravan",
      "آخرى",
    ],
  },
  {
    label: "سيتروين",
    value: "سيتروين",
    models: [
      "الكل",
      "AX",
      "بيرلينغو",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C8",
      "ديسباتش",
      "DS 3",
      "DS 4",
      "DS 7",
      "DS 21",
      "Jumper",
      "Saxo",
      "SpaceTourer",
      "آخرى",
    ],
  },
  {
    label: "CMC",
    value: "CMC",
    models: ["الكل", "Veryca", "27", "آخرى"],
  },
  {
    label: "دودج",
    value: "دودج",
    models: [
      "الكل",
      "أفينجر",
      "كاليبر",
      "تشالنجر",
      "تشارجر",
      "Dakota",
      "دارت",
      "دورانغو",
      "غراند كارافان",
      "إنتريبيد",
      "جورنّي",
      "ماغنوم",
      "نيون",
      "نيترو",
      "رام",
      "ستراتوس",
      "فيبر",
      "آخرى",
    ],
  },
  {
    label: "دونغفنغ",
    value: "دونغفنغ",
    models: [
      "الكل",
      "A9",
      "AX3",
      "AX5",
      "AX7",
      "دنجو ",
      "F12",
      "F5",
      "فنجون ",
      "جويير ",
      "K10",
      "M5",
      "ريتش ",
      "سوكون ",
      "V3",
      "ووريور",
      "آخرى",
    ],
  },
  {
    label: "إكسيد ",
    value: "إكسيد",
    models: [
      "الكل",
      "EOL",
      "EOL Pro",
      "GL6",
      "LSE",
      "LX",
      "VX",
      "VX Plus",
      "آخرى",
    ],
  },

  {
    label: "فينغون",
    value: "فينغون",
    models: [
      "الكل",
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
      "آخرى",
    ],
  },
  {
    label: "فيراري",
    value: "فيراري",
    models: [
      "الكل",
      "348",
      "488 بيستا",
      "488 سبايدر",
      "812 GTS",
      "812 سوبر فاست",
      "كاليفورنيا",
      "كاليفورنيا تي",
      "دايتونا  SP3",
      "دينو",
      "إف 12 برلينيتا",
      "F12 TDF",
      "F8 سبايدر",
      "إف 8 تريبيوتو",
      "جي تي سي 4 لوسو",
      "لافيراري",
      "لافيراري أبيرتا",
      "مونزا  SP1",
      "مونزا  SP2",
      "P80/C",
      "بورتوفينو إم",
      "روما",
      "SF90 سبايدر",
      "SF90 سترادالي",
      "SP3",
      "سوبر فاست",
      "آخرى",
    ],
  },

  {
    label: "فيات",
    value: "فيات",
    models: [
      "الكل",
      "500",
      "500L",
      "500X",
      "124",
      "دوكاتو",
      "باندا ",
      "سكودو ",
      "تالينتو ",
      "تيبو",
      "آخرى",
    ],
  },
  {
    label: "فورد",
    value: "فورد",
    models: [
      "الكل",
      "برونكو",
      "سي-ماكس",
      "إدج",
      "إسكيب",
      "إيفرست",
      "إكسبلورر",
      "إف-150",
      "إف-150 رابتور",
      "إف-250",
      "إف-350",
      "فوكاس",
      "فيوجن",
      "جراند سي-ماكس",
      "مافريك",
      "مونديو",
      "موستانغ",
      "رينجر",
      "تاونوس",
      "توريز",
      "آخرى",
    ],
  },
  {
    label: "فورثينغ",
    value: "فورثينغ",
    models: [
      "الكل",
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
      "آخرى",
    ],
  },
  {
    label: "فوتون",
    value: "فوتون",
    models: ["الكل", "SUP", "Tunland", "View", "آخرى", "توريز"],
  },
  {
    label: "جي أي سي",
    value: "جي أي سي",
    models: [
      "الكل",
      "أيون LX",
      "أيون S",
      "أيون V",
      "أركانا",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "هافال  F5",
      "هافال  F7",
      "هافال  H6",
      "هافال  H9",
      "ترمبشي  GA6",
      "ترمبشي  GA8",
      "ترمبشي  GS5",
      "ترمبشي  M6",
      "ZHONGYI",
      "آخرى",
    ],
  },
  {
    label: "جيلي",
    value: "جيلي",
    models: [
      "الكل",
      "Emgrand",
      "Farizon",
      "Emgrand",
      "Farizon",
      "GCr",
      "GCY",
      "GXr",
      "Geometry C",
      "Monjaro",
      "Okvango",
      "Preface",
      "Starray",
      "آخرى",
    ],
  },
  {
    label: "جيسنيسيس",
    value: "جيسنيسيس",
    models: [
      "الكل",
      "كوبيه",
      "G70",
      "G80",
      "G90",
      "GV60",
      "GV70",
      "GV80",
      "آخرى",
    ],
  },
  {
    label: "جي إم سي",
    value: "جي إم سي",
    models: [
      "الكل",
      "أكاديا",
      "كانيون",
      "إنكانتوا",
      "همر",
      "جيمي",
      "بيك اب",
      "سوبربان",
      "سافانا",
      "سييرا",
      "تيراين",
      "يوكون",
      "آخرى",
    ],
  },
  {
    label: "جريت وول",
    value: "جريت وول",
    models: [
      "الكل",
      "King Kong",
      "Poer",
      "Wey Gaoshan",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 6",
      "Wingle 7",
      "آخرى",
    ],
  },
  {
    label: "هافال",
    value: "هافال",
    models: ["الكل", "Dargo", "H2", "H6", "H8", "H9", "Jolion", "آخرى"],
  },
  {
    label: "هينو",
    value: "هينو",
    models: ["All"],
  },
  {
    label: "HiPhi",
    value: "HiPhi",
    models: ["All", "X", "Z", "Other"],
  },
  {
    label: "هوندا",
    value: "هوندا",
    models: [
      "الكل",
      "أكورد",
      "سيتي",
      "سيفيك",
      "Crider",
      "Crosstour",
      "Clarity",
      "CR-V",
      "ENP1",
      "ENP2",
      "HR-V",
      "بيك آب",
      "Fit",
      "بايلوت",
      "اوديسي",
      "S2000",
      "فان",
      "ليجند",
      "ENS1",
      "آخرى",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    models: [
      "الكل",
      "W-HS9",
      "E-QM5",
      "H5",
      "H7",
      "H9",
      "HS5",
      "HS7",
      "HS9",
      "Ousado",
      "آخرى",
    ],
  },
  {
    label: "هيونداي",
    value: "هيونداي",
    models: [
      "أكسنت",
      "اتوس",
      "افانتي",
      "ازيرا",
      "كاسبر",
      "سينتينتال",
      "كوبيه",
      "كريتا",
      "ألنترا",
      "انتوراج",
      "اكسيل",
      "جالوبر",
      "جينيسيس",
      "غيتز",
      " سانتا فيه",
      "سوناتا",
      "توكسون",
      "فولستر",
      "فيرنا",
      "فيراكروزر",
      "فينيو",
      "ستاريا",
      "مايتي",
      "كونا",
      "ايونيك",
      "10جراند أي ",
      "H1",
      "H100",
      "i10",
      "i20",
      "i30",
      "i40",
      "i40",
      "i40",
      "i40",
      "آخرى",
    ],
  },
  {
    label: "INEOS",
    value: "INEOS",
    models: ["الكل"],
  },
  {
    label: "إنفينيتي",
    value: "إنفينيتي",
    models: [
      "الكل",
      "Q50",
      "Q60",
      "Q70",
      "Q80",
      "QX30",
      "QX50",
      "QX55",
      "QX60",
      "QX80",
      "آخرى",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    models: [
      "الكل",
      "اميغو",
      "أسندر ",
      "D-Max",
      "F-سلسلة ",
      "Impulse",
      "MU-X",
      "N-سلسلة",
      "NPR",
      " i-سلسلة ",
      "روديو ",
      "تروبر ",
      "آخرى",
    ],
  },
  {
    label: "جاك ",
    value: "جاك",
    models: [
      "الكل",
      "HK6730",
      "J4",
      "J5",
      "J6",
      "J7",
      "JS4",
      "JS6",
      "M1",
      "M4",
      "M5",
      "S3",
      "S7",
      "T6 Pickup",
      "T8",
      "آخرى",
    ],
  },
  {
    label: "جاكوار",
    value: "جاكوار",
    models: [
      "الكل",
      "E-Pace",
      "F-Pace",
      "F-TYPE",
      "I-PACE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK-8",
      "XKR",
      "آخرى",
    ],
  },
  {
    label: "جيب",
    value: "جيب",
    models: [
      "الكل",
      "شيروكي",
      "كوماندر",
      "كومباس",
      "غلادياتور",
      " جراند شيروكي ",
      "غراند واغونيير",
      "باتريوت",
      "ليبرتي",
      "رينيغيد",
      "واغونيير",
      "رانجلر",
    ],
  },
  {
    label: "جيتور",
    value: "جيتور",
    models: ["الكل", "T1", "T2", "X50", "X70", "X90", "X95", "آخرى"],
  },
  {
    label: "JMC",
    value: "JMC",
    models: [
      "الكل",
      "باودا",
      "كارينغ",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "لاند ويند",
      "تيسون",
      "فيغوس",
      "آخرى",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    models: ["E5", "EQ1", "K1", "K2", "K3", "K6", "K7", "S3", "S5", "S7", "S9"],
  },
  {
    label: "كيا",
    value: "كيا",
    models: [
      "الكل",
      "بونجو",
      "كادينزا",
      "كارينز",
      "كرنفال",
      "سيراتو",
      "موهاف",
      "نيرو",
      "اوبريوس",
      "أوبتيما",
      "بيجاس",
      "بيكانتو",
      "ريو",
      "روندو",
      "سيدونا",
      "سورنتو",
      "سول",
      "سبورتاج",
      "ستينجر",
      "سيفيا",
      "تيلورايد",
      "K3",
      "k5",
      "k8",
      "k9",
      "k900",
      "E75",
      "E76",
      "E79",
      "k900",
      "آخرى",
    ],
  },
  {
    label: "كوينيجسيج",
    value: "كوينيجسيج",
    models: [
      "الكل",
      "أغيرا",
      "CC8S",
      "CC8S",
      "CCGT",
      "CCR",
      "CCX",
      "CCX-R",
      "جيميرا",
      "جيسكو",
      "One:1",
      "كواتروبورتي",
      "ريجيرا",
      "آخرى",
    ],
  },
  {
    label: "لامبورغيني",
    value: "لامبورغيني",
    models: [
      "الكل",
      "Asterion",
      "آڤنتادور",
      "سنترينو",
      "كونتاش",
      "إستوك",
      "گالاردو",
      "هوراكان",
      "مرشيلاغو",
      "ريفينتون",
      "سيان",
      "أوروس",
      "آخرى",
    ],
  },
  {
    label: "لاند روفر / رانج روفر",
    value: "لاند روفر / رانج روفر",
    models: [
      "الكل",
      " رانج روفر فوج",
      " رانج روفر إيفوك",
      " رانج روفر سبورت",
      "رانج روفر فيلار",
      "ديفندر",
      "ديسكفري",
      "ديسكفري سبورت",
      "فريلاندر",
      "LR2",
      "LR3",
      "LR4",
      "آخرى",
    ],
  },
  {
    label: "لكزس",
    value: "لكزس",
    models: [
      "الكل",
      "CT فئة",
      "ESفئة ",
      "GSفئة ",
      "GX فئة ",
      "ISفئة ",
      "LC 500",
      "LFA",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "SC",
      "UX",
      "آخرى",
    ],
  },
  {
    label: "لوتس",
    value: "لوتس",
    models: [
      "الكل",
      "Elan",
      "Eletre",
      "Elise",
      "Emeya",
      "Emira",
      "Esprit",
      "Evora",
      "Exige",
      "آخرى",
    ],
  },
  {
    label: "لوسيد",
    value: "لوسيد",
    models: ["الكل"],
  },
  {
    label: "ماهيندرا",
    value: "ماهيندرا",
    models: [
      "الكل",
      "ألتوراس G4",
      "بوليرو",
      "eKUV100",
      "فوريوا",
      "KUV100",
      "مارازو",
      "بيك أب",
      "سكورتب",
      "سكورتب-N",
      "ثار",
      "TUV300",
      "XUV300",
      "XUV700",
      "زيليو",
      "آخرى",
    ],
  },
  {
    label: "مازيراتي",
    value: "مازيراتي",
    models: [
      "الكل",
      "ألفييري",
      "غيبلي",
      "غراند كابريو",
      "غراند توريسمو",
      "ليفانتي",
      "إم سي 20",
      "كواتروبورتي",
      "آخرى",
    ],
  },
  {
    label: "مازدا ",
    value: "مازدا",
    models: [
      "الكل",
      "2",
      "3",
      "323",
      "6",
      "626",
      "929",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-7",
      "CX-9",
      "CX-90",
      "MX-5",
      "بيك اب",
      "آخرى",
    ],
  },
  {
    label: "ماكلارين",
    value: "ماكلارين",
    models: [
      "الكل",
      "540C",
      "570GT",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "765LT",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
      "SLR",
      "آخرى",
    ],
  },
  {
    label: "مرسيدس بنز",
    value: "مرسيدس بنز",
    models: [
      "الكل",
      "A-فــئة ",
      "B-فــئة ",
      "C-فــئة ",
      "E-فــئة ",
      "G-فــئة ",
      "M-فــئة ",
      "R-فــئة ",
      "S-فــئة ",
      "V-فــئة ",
      "X-فــئة ",
      "CL-فئة",
      "CLA",
      "CLC",
      "CLE-فئة",
      "CLK-فئة",
      "CLS-فئة",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQG",
      "EQS",
      "EQV",
      "GL-فئة",
      "GLA",
      "GLB",
      "GLC",
      "GLE ",
      "GLK ",
      "GLS ",
      "GT",
      "S580e",
      "SEC-Class",
      "SEL-Class",
      "SL-Class",
      "SLC",
      "SLS",
      "Sprinter",
      "Viano",
      "Vito",
      "آخرى",
    ],
  },
  {
    label: "ميتسوبيشي",
    value: "ميتسوبيشي",
    models: [
      "الكل",
      "ASX",
      "اتراج ",
      "كولت ",
      "اكلبس",
      "اكلبس كروز",
      "جالانت ",
      "i-MiEV",
      "لانسر ",
      "مونتيرو ",
      "ميراج ",
      "أوتلاندر ",
      "باجيرو ",
      "اكسباندر ",
      "ابفوليوشن ",
      "3000GT",
      "Canter",
      "فورتس",
      "L200",
      "Van",
      "آخرى",
    ],
  },
  {
    label: "Mini",
    value: "Mini",
    models: [
      "الكل",
      "كلوبمان",
      "كوبر",
      "كوبر كلوبمان",
      "كنتري مان",
      "كوبيه",
      "مايفير",
      "بيسمان",
      "رودستر",
      "آخرى",
    ],
  },
  {
    label: "نيسان",
    value: "نيسان",
    models: [
      "الكل",
      "ألتيما",
      "ارمادا",
      "صني",
      "إكس تريل",
      "كيكس",
      "سينترا",
      "باثفايندر",
      "باترول",
      "جي تي-آر",
      "إكس تيرا",
      "نافارا",
      "370Z",
      "جوك",
      "مورانو",
      "قاشقاي",
      "كوست",
      "روج",
      "ماكسيما",
      "بيك اب",
      "مايكرا",
      "تينا",
      "ليف",
      "فوجا",
      "NV350",
      "NV200",
      "فرونتير",
      "سكاي لاين",
      "تيتان",
      "فان",
      "آخرى",
    ],
  },
  {
    label: "بيجو",
    value: "بيجو",
    models: [
      "الكل",
      "108",
      "207",
      "208",
      "301",
      "307",
      "308",
      "407",
      "408",
      "504",
      "508",
      "607",
      "2008",
      "3008",
      "5008",
      "اكسبرت",
      "ريفتر",
      "بارتنر",
      "ترافلر",
      "بوكسر",
      "آخرى",
    ],
  },
  {
    label: "بورشه",
    value: "بورشه",
    models: [
      "الكل",
      "911",
      "تايكان",
      "ماكان",
      "كايين",
      "بوكستر",
      "كايمان",
      "باناميرا",
      "918",
      "928",
      "718",
      "آخرى",
    ],
  },
  {
    label: "رام",
    value: "رام",
    models: [
      "All",
      "1500",
      "1500 Classic",
      "1500 TRX",
      "2500",
      "Warlock",
      "Other",
    ],
  },
  {
    label: "رينو ",
    value: "رينو ",
    models: [
      "الكل",
      "الجميع",
      "Arkana",
      "Captur",
      "كليو",
      "دوكر",
      "داستر",
      "ايسكيب",
      "فان اكسبرس",
      "Fluence",
      "كوليوس",
      "Laguna",
      "لوغان",
      "ماستر",
      "ميغان",
      "سيمبول",
      "Tailsman",
      "Trafic",
      "توينغو",
      "ماستر",
      "تويزي",
      "زوي",
      "Tailsman",
      "آخرى",
    ],
  },
  {
    label: "رولز رويس",
    value: "رولز رويس",
    models: [
      "الكل",
      "كولينان",
      "داون",
      "غوست",
      "فانتوم",
      "سيلفر سبير",
      "سيلفر كلاود",
      "سيلفر داون",
      "سيلفر سيراف",
      "سيلفر شادو",
      "سيلفر سبيريت",
      "سبكتر",
      "رايث",
      "آخرى",
    ],
  },
  {
    label: "سكودا",
    value: "سكودا",
    models: [
      "الكل",
      "فابيا",
      "كاميك",
      "كاروك",
      "كودياك",
      "كوشاك",
      "أوكتافيا",
      "رابيد",
      "رومستر",
      "سكالا",
      "سوبيرب",
      "ياتي",
      "آخرى",
    ],
  },
  {
    label: "تسلا",
    value: "تسلا",
    models: ["All", "Model S", "Model 3", "Model X", "Model Y", "Other"],
  },
  {
    label: "تويوتا",
    value: "تويوتا",
    models: [
      "الكل",
      "4رانر",
      "86",
      "ألفارد",
      "أوريون",
      "أفالون",
      "أفانزا",
      "أفينسيس",
      "BZ4X",
      "C-HR",
      "كامري",
      "سيلكا",
      "كوستر",
      "كورولا",
      "كورونا",
      "كريسيدا",
      "كراون",
      "إيكو",
      "إف جي كروزر",
      "فورتشنر",
      "فرونت لاندر",
      "GR86",
      "جرانفيا",
      "هايس",
      "هايلاندر",
      "هيلكس",
      "آي كيو",
      "إنوفا",
      "لاند كروزر",
      "ليفين",
      "MR2",
      "ميراى",
      "بيك أب",
      "برادو",
      "بريفيا",
      "بريوس",
      "رايز",
      "راف 4",
      "روميونو",
      "راش",
      "سيون",
      "سيكويا",
      "سيينا",
      "سوبرا",
      "تاكوما",
      "تيرسل",
      "توندر",
      "أوربان كروزر",
      "فيليز",
      "فينزا",
      "فيتس",
      "ويغو",
      "إكس إيه",
      "ياريس",
      "زيلاس",
      "BZ3",
      "iA",
      "أخرى",
    ],
  },
  {
    label: "فولكس فاجن",
    value: "فولكس فاجن",
    models: [
      "الكل",
      "Arteon",
      "Atlas",
      "Beetle",
      "Bora",
      "Corrado",
      "Caddy",
      "Crafter",
      "E-Lavida",
      "EOS",
      "Eurovan",
      "GTI",
      "غولف",
      "ID.3",
      "ID.4",
      "ID.6",
      "ID.7",
      "جيتا",
      "Multivan",
      "فايتون",
      "بولو",
      "روتان",
      "سيروكو",
      "شاران",
      "T-Roc",
      "Tayron",
      "Teramont",
      "Tiguan",
      "توارك",
      "ترانسبورتر",
      "فينتو",
      "فيلوران",
      "آخرى",
    ],
  },
  {
    label: "فولفو",
    value: "فولفو",
    models: [
      "الكل",
      "C-Class",
      "C40",
      "S-Class",
      "S90",
      "V-Class",
      "V90",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC70",
      "XC90",
      "آخرى",
    ],
  },
  {
    label: "Xiaomi",
    value: "Xiaomi",
    models: ["الكل"],
  },
  {
    label: "Zeekr",
    value: "Zeekr",
    models: ["الكل", "001", "007", "009", "X", "آخرى"],
  },
];
