export const makes = [
  {
    label: "Abarth",
    value: "Abarth",
    models: [
      "124 GT",
      "124 Spider",
      "500C",
      "595",
      "595 Competizione",
      "595 Esseesse",
      "595 Pista",
      "595 Turismo",
      "695",
      "695 Biposto",
      "Punto",
      "Tributo Ferrari",
    ],
  },

  {
    label: "Alfa Romeo",
    value: "Alfa Romeo",
    models: [
      "147",
      "156",
      "159",
      "164",
      "2000",
      "33",
      "33 Stradale",
      "4C",
      "75",
      "90",
      "Alfasud",
      "Alfetta",
      "Brera",
      "Duetto",
      "Giulia",
      "Giulia Quadrifoglio",
      "Giulietta",
      "GTV",
      "MiTo",
      "Montreal",
      "Spider",
      "Stelvio",
      "Stelvio Quadrifoglio",
      "SZ",
    ],
  },
  {
    label: "Aston Martin",
    value: "Aston Martin",
    models: [
      "Cygnet",
      "DB10",
      "DB11",
      "DBR1",
      "DBS Superleggera",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Valhalla",
      "Vantage",
      "Victor",
    ],
  },
  {
    label: "Audi",
    value: "Audi",
    models: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "e-tron",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "R8",
      "RS3",
      "RS5",
      " RS7",
      "TT",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    models: ["Model 11", "Model 12", "Model 13", "Model 14"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    models: [
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
    ],
  },
  {
    label: "Bentley",
    value: "Bentley",
    models: [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental GT",
      "Flying Spur",
      "Mulsanne",
      "R-Type",
      "S1",
      "S2",
      "Speed Six",
      "T-Series",
    ],
  },
  {
    label: "Bestune",
    value: "Bestune",
    models: [
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
    ],
  },
  {
    label: "BMW",
    value: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "E46 M3",
      "i Series",
      "Series 7",
      "X Series",
      "Z Series",
    ],
  },
  {
    label: "Bugatti",
    value: "Bugatti",
    models: [
      "Bolide",
      "Centodieci",
      "Chiron",
      "Chiron Pur Sport",
      "Chiron Super Sport",
      "Divo",
      "EB110",
      "La Finale",
      "La Voiture Noire",
      "Type 251",
      "Type 35",
      "Type 57",
      "Veyron",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    models: [
      "Dolphin",
      "E3",
      "e6",
      "FO",
      "G3",
      "Han",
      "L3",
      "Qin",
      "S3",
      "Seal",
      "Song",
      "T3",
      "Tang",
      "Yuan",
    ],
  },
  {
    label: "Cadillac",
    value: "Cadillac",
    models: ["CT4", "CT5", "CT6", "Escalade", "Lyriq", "CT4", "CT5", "CT6"],
  },
  {
    label: "Changan",
    value: "Changan",
    models: [
      "Alsvin",
      "Benni",
      "CS15",
      "CS35",
      "CS55",
      "CS75",
      "Eado",
      "Hunter",
      "Kaicene",
      "Oushang",
      "Raeton",
      "Star 5",
      "Uni-K",
      "Uni-T",
    ],
  },
  {
    label: "Chery",
    value: "Chery",
    models: [
      "Arrizo",
      "Eastar",
      "Exeed",
      "Fulwin",
      "Karry",
      "QQ",
      "Tiggo",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
    ],
  },
  {
    label: "Chevrolet",
    value: "Chevrolet",
    models: [
      "Avalanche",
      "Blazer",
      "Camaro",
      "Caprice",
      "Chevelle",
      "Corvette",
      "Equinox",
      "Impala",
      "Malibu",
      "Monte Carlo",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "Tahoe",
      "Traverse",
      "Trax",
      "Volt",
    ],
  },
  {
    label: "Chrysler",
    value: "Chrysler",
    models: [
      "200",
      "300",
      "300C",
      "300M",
      "Aspen",
      "Cirrus",
      "Concorde",
      "Cordoba",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Pacifica",
      "Prowler",
      "PT Cruiser",
      "Sebring",
      "Voyager",
    ],
  },
  {
    label: "Citroen",
    value: "Citroen",
    models: [
      "Ami",
      "Berlingo",
      "C-Elysee",
      "C3",
      "C4",
      "C5",
      "C5 X",
      "C6",
      "Dispatch",
      "DS 3",
      "DS 4",
      "DS 7",
      "Jumpy",
      "Picasso",
      "Spacetourer",
    ],
  },
  { label: "CMC", value: "CMC", models: ["Veryca"] },
  {
    label: "Dodge",
    value: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Challenger SRT Hellca",
      "Charger",
      "Dakota",
      "Dart",
      "Durango",
      "Durango RT",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stratus",
      "Viper",
    ],
  },
  {
    label: "DongFeng",
    value: "DongFeng",
    models: [
      "A9",
      "AX3",
      "AX5",
      "AX7",
      "Dingo",
      "F12",
      "F5",
      "Fengon",
      "Joyear",
      "K10",
      "M5",
      "Rich",
      "Sokon",
      "V3",
      "Warrior",
    ],
  },
  {
    label: "Exeed",
    value: "Exeed",
    models: ["EOL", "EOL Pro", "GL6", "LSE", "LX", "VX", "VX Plus"],
  },

  {
    label: "Fengon",
    value: "Fengon",
    models: [
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
    ],
  },
  {
    label: "Ferrari",
    value: "Ferrari",
    models: [
      "348",
      "488 Pista",
      "488 Spider",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "Daytona SP3",
      "Dino",
      "F12 Berlinetta",
      "F12 TDF",
      "F8 Spider",
      "F8 Tributo",
      "GTC4Lusso",
      "LaFerrari",
      "LaFerrari Aperta",
      "Monza SP1",
      "Monza SP2",
      "P80/C",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "SP3",
      "Superfast",
    ],
  },

  {
    label: "Fiat",
    value: "Fiat",
    models: [
      "500",
      "500L",
      "500X",
      "Ducato",
      "Panda",
      "Scudo",
      "Talento",
      "Tipo",
    ],
  },
  {
    label: "Ford",
    value: "Ford",
    models: [
      "Bronco",
      "Bronco Sport",
      "C-Max",
      "Edge",
      "Edge Sport",
      "Escape",
      "Everest Hybrid",
      "Explorer",
      "F-150",
      "F-150 Raptor",
      "F-250",
      "F-350",
      "Focus",
      "Fusion",
      "Grand C-Max",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Ranger",
      "Taunus",
      "Taurus",
    ],
  },
  {
    label: "Forthing",
    value: "Forthing",
    models: [
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
    ],
  },
  {
    label: "Foton",
    value: "Foton",
    models: [
      "Aumark",
      "Forland",
      "G9",
      "Gratour",
      "Ollin",
      "Sauvana",
      "Transits",
      "Tunland",
      "View",
      "Weichai",
    ],
  },
  {
    label: "GAC",
    value: "GAC",
    models: [
      "Aion LX",
      "Aion S",
      "Aion V",
      "Arkana",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "Haval F5",
      "Haval F7",
      "Haval H6",
      "Haval H9",
      "Trumpchi GA6",
      "Trumpchi GA8",
      "Trumpchi GS5",
      "Trumpchi M6",
      "ZHONGYI",
    ],
  },
  {
    label: "Geely",
    value: "Geely",
    models: [
      "Aion",
      "Haifeng",
      "Haijie",
      "Jiaji EV",
      "KX3",
      "Lykov EV",
      "Meizu ES6",
      "Meizu ES6 Plus",
      "Meizu EVO",
      "Pionner",
      "Pionner Plus",
      "Vision X50",
      "Xing Rui",
      "Xingyue",
      "Xingyue L",
    ],
  },
  {
    label: "Genesis",
    value: "Genesis",
    models: [
      "Electrified G80",
      "Electrified GV70",
      "G70",
      "G80",
      "G90",
      "GV70",
      "GV80",
    ],
  },
  {
    label: "GMC",
    value: "GMC",
    models: [
      "Acadia",
      "Canyon",
      "Encanto",
      "Envoy",
      "Envoy SLT",
      "Envoy XUV",
      "HUMMER H2",
      "Savana",
      "Sierra",
      "Terrain",
    ],
  },
  {
    label: "Great Wall",
    value: "Great Wall",
    models: [
      "Coolbear",
      "Heimao",
      "Pao",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 7",
    ],
  },
  {
    label: "Haval",
    value: "Haval",
    models: [
      "CUV H",
      "F7 Plus",
      "F7x",
      "H2",
      "H6",
      "H7",
      "H9",
      "H9 LUX",
      "Jolion",
      "Jolion Hybrid",
      "M6",
    ],
  },
  {
    label: "Hino",
    value: "Hino",
    models: ["Hino 300", "Hino 500", "Hino 600", "Hino Dutro"],
  },
  { label: "HiPhi", value: "HiPhi", models: ["HiPhi X", "HiPhi Y", "HiPhi Z"] },
  {
    label: "Honda",
    value: "Honda",
    models: [
      "Accord",
      "Civic",
      "Civic Si",
      "Civic Type R",
      "Clarity",
      "CR-V",
      "Fit",
      "Insight",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    models: ["E-HS9", "E-QM5", "H5", "H9L", "HS3", "HS5", "HS7", "L5"],
  },
  {
    label: "Hyundai",
    value: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Genesis",
      "Ioniq",
      "Kona",
      "Nexo",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Sonata",
      "Tucson",
      "Veloster",
    ],
  },
  { label: "INEOS", value: "INEOS", models: ["Grenadier"] },
  {
    label: "Infiniti",
    value: "Infiniti",
    models: [
      "Q50",
      "Q60",
      "Q70",
      "Q80",
      "QX30",
      "QX50",
      "QX55",
      "QX60",
      "QX80",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    models: [
      "Amigo",
      "Ascender",
      "D-Max",
      "Elf",
      "F-Series",
      "Impulse",
      "MU-X",
      "N-Series",
      "NPR",
      "P'up",
      "Rodeo",
      "Trooper",
    ],
  },
  {
    label: "Jac",
    value: "Jac",
    models: [
      "J4",
      "J6",
      "J7",
      "Refine S3",
      "Refine S5",
      "S2",
      "S3",
      "S5",
      "S7",
      "T6",
      "T8",
    ],
  },
  {
    label: "Jaguar",
    value: "Jaguar",
    models: [
      "E-Pace",
      "E-Pace R-Dynamic",
      "F-PACE",
      "F-PACE SVR",
      "F-TYPE",
      "F-TYPE R",
      "F-TYPE S",
      "F-TYPE SVR",
      "I-PACE",
      "I-PACE HSE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XF Sportbrake",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK F-TYPE R",
      "XKR",
    ],
  },
  {
    label: "Jeep",
    value: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "Jetour",
    value: "Jetour",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "JMC",
    value: "JMC",
    models: [
      "Baoda",
      "Carrying",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "Landwind",
      "Teshun",
      "Vigus",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    models: ["E5", "EQ1", "K1", "K2", "K3", "K6", "K7", "S3", "S5", "S7", "S9"],
  },
  {
    label: "Kia",
    value: "Kia",
    models: [
      "Forte",
      "Niro",
      "Optima",
      "Rio",
      "Rondo",
      "Sedona",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
    ],
  },
  {
    label: "Koenigsegg",
    value: "Koenigsegg",
    models: [
      "Agera",
      "CC8S",
      "CCR",
      "CCX",
      "CCX-R",
      "Gemera",
      "Jesko",
      "One:1",
      "Quattroporte",
      "Regera",
    ],
  },
  {
    label: "Lamborghini",
    value: "Lamborghini",
    models: [
      "Asterion",
      "Aventador",
      "Aventador S",
      "Centenario",
      "Countach",
      "Estoque",
      "Gallardo",
      "Gallardo Spyder",
      "Huracan",
      "Huracán",
      "Huracán EVO",
      "Huracán Spyder",
      "Murciélago",
      "Reventón",
      "Sián",
      "Urus",
      "Urus Performante",
    ],
  },
  {
    label: "Land Rover",
    value: "Land Rover",
    models: [
      "Range Rover",
      "Defender",
      "Discovery",
      "Dicovery Sport",
      "Range Rover Sport",
    ],
  },
  {
    label: "Lexus",
    value: "Lexus",
    models: [
      "ES",
      "GS",
      "IS",
      "LC 500",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "UX",
    ],
  },
  {
    label: "Lotus",
    value: "Lotus",
    models: [
      "Carlton",
      "Eclat",
      "Elan",
      "Elise",
      "Elite",
      "Esprit",
      "Europa",
      "Evora",
      "Exige",
      "Seven",
    ],
  },
  { label: "Lucid", value: "Lucid", models: ["Air", "Gravity"] },
  {
    label: "Mahindra",
    value: "Mahindra",
    models: [
      "Alturas G4",
      "Bolero",
      "eKUV100",
      "Furio",
      "KUV100",
      "Marazzo",
      "Pick Up",
      "Scorpio",
      "Scorpio-N",
      "Thar",
      "TUV300",
      "XUV300",
      "XUV700",
      "Xylo",
    ],
  },
  {
    label: "Maserati",
    value: "Maserati",
    models: [
      "Alfieri",
      "Biturbo",
      "Ghibli",
      "GranCabrio",
      "Granturismo",
      "Levante",
      "MC20",
      "Quattroporte",
      "Shamal",
    ],
  },
  {
    label: "Mazda",
    value: "Mazda",
    models: [
      "Mazda CX-3",
      "Mazda CX-30",
      "Mazda CX-5",
      "Mazda CX-50",
      "Mazda CX-9",
      "Mazda MX-5 Miata",
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "MX-5 Miata",
    ],
  },
  {
    label: "McLaren",
    value: "McLaren",
    models: [
      "12C Spider",
      "540C",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "GTR",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
    ],
  },
  {
    label: "Mercedes-Benz",
    value: "Mercedes-Benz",
    models: [
      "A 200",
      "A-Class",
      "AMG CLA-Class",
      "AMG GT",
      "AMG GT Roadster",
      "B-Class",
      "C-Class",
      "CLA",
      "Class S",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQS",
      "G-Class",
      "GLA",
      "GLC",
      "GLC300",
      "GLC350e 4MATIC",
      "GLE",
      "GLS",
      "S-Class",
      "SL",
      "Sprinter",
      "V-Class",
      "X-Class",
    ],
  },
  {
    label: "Mitsubishi",
    value: "Mitsubishi",
    models: [
      "3000GT",
      "ASX",
      "Carisma",
      "Colt",
      "Eclipse",
      "Galant",
      "i-MiEV",
      "Lancer",
      "Montero",
      "Outlander",
      "Pajero",
      "RVR",
      "Shogun",
      "Xpander Cross",
    ],
  },
  {
    label: "Nissan",
    value: "Nissan",
    models: [
      "370Z",
      "370Z Nismo",
      "Altima",
      "Armada",
      "Frontier",
      "GT-R",
      "Juke",
      "Maxima",
      "Murano",
      "Pathfinder",
      "Rogue",
      "Sentra",
      "Titan",
      "Versa",
    ],
  },
  { label: "Peugeot", value: "Peugeot", models: ["3008", "5008"] },
  { label: "Porsche", value: "Porsche", models: ["911", "Cayenne", "Macan"] },
  { label: "RAM", value: "RAM", models: ["1500", "2500"] },
  {
    label: "Renault",
    value: "Renault",
    models: ["Grand Scenic", "Megane", "Talisman"],
  },
  {
    label: "Rolls-Royce",
    value: "Rolls-Royce",
    models: [
      "Corniche",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Spectre",
      "Wraith",
    ],
  },
  {
    label: "Skoda",
    value: "Skoda",
    models: [
      "Citigo-e iV",
      "Enyaq iV",
      "Fabia",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  {
    label: "Tesla",
    value: "Tesla",
    models: ["Model S", "Model 3", "Model X", "Model Y"],
  },
  {
    label: "Toyota",
    value: "Toyota",
    models: ["Corolla", "Camry", "RAV4 Adventure", "Supra 191 Edition"],
  },
  {
    label: "Volkswagen",
    value: "Volkswagen",
    models: [
      "Beetle",
      "Bora",
      "Corrado",
      "EOS",
      "Eos CC",
      "Fox",
      "Golf",
      "Golf Estate",
      "Golf GTI",
      "Golf Hatchback",
      "Golf R",
      "Golf SV",
      "ID3",
      "Jetta",
      "Jetta GLI",
      "Passat",
      "Passat CC",
      "Passat Estate",
      "Phaeton",
      "Polo",
      "Rabbit",
      "RNS",
      "Scirocco",
      "Sharan",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  { label: "Volvo", value: "Volvo", models: ["XC90", "S60", "V60"] },
  { label: "Xiaomi", value: "Xiaomi", models: ["SU7"] },
  { label: "Zeekr", value: "Zeekr", models: ["001", "X"] },
];
export const arabicMakes = [
  {
    label: "Abarth",
    value: "Abarth",
    models: [
      "124 GT",
      "124 Spider",
      "500C",
      "595",
      "595 Competizione",
      "595 Esseesse",
      "595 Pista",
      "595 Turismo",
      "695",
      "695 Biposto",
      "Punto",
      "Tributo Ferrari",
    ],
  },

  {
    label: "Alfa Romeo arabic",
    value: "Alfa Romeo",
    models: [
      "147",
      "156",
      "159",
      "164",
      "2000",
      "33",
      "33 Stradale",
      "4C",
      "75",
      "90",
      "Alfasud",
      "Alfetta",
      "Brera",
      "Duetto",
      "Giulia",
      "Giulia Quadrifoglio",
      "Giulietta",
      "GTV",
      "MiTo",
      "Montreal",
      "Spider",
      "Stelvio",
      "Stelvio Quadrifoglio",
      "SZ",
    ],
  },
  {
    label: "Aston Martin",
    value: "Aston Martin",
    models: [
      "Cygnet",
      "DB10",
      "DB11",
      "DBR1",
      "DBS Superleggera",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Valhalla",
      "Vantage",
      "Victor",
    ],
  },
  {
    label: "Audi",
    value: "Audi",
    models: [
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "e-tron",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "R8",
      "RS3",
      "RS5",
      " RS7",
      "TT",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    models: ["Model 11", "Model 12", "Model 13", "Model 14"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    models: [
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
    ],
  },
  {
    label: "Bentley",
    value: "Bentley",
    models: [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental GT",
      "Flying Spur",
      "Mulsanne",
      "R-Type",
      "S1",
      "S2",
      "Speed Six",
      "T-Series",
    ],
  },
  {
    label: "Bestune",
    value: "Bestune",
    models: [
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
    ],
  },
  {
    label: "BMW",
    value: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "E46 M3",
      "i Series",
      "Series 7",
      "X Series",
      "Z Series",
    ],
  },
  {
    label: "Bugatti",
    value: "Bugatti",
    models: [
      "Bolide",
      "Centodieci",
      "Chiron",
      "Chiron Pur Sport",
      "Chiron Super Sport",
      "Divo",
      "EB110",
      "La Finale",
      "La Voiture Noire",
      "Type 251",
      "Type 35",
      "Type 57",
      "Veyron",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    models: [
      "Dolphin",
      "E3",
      "e6",
      "FO",
      "G3",
      "Han",
      "L3",
      "Qin",
      "S3",
      "Seal",
      "Song",
      "T3",
      "Tang",
      "Yuan",
    ],
  },
  {
    label: "Cadillac",
    value: "Cadillac",
    models: ["CT4", "CT5", "CT6", "Escalade", "Lyriq", "CT4", "CT5", "CT6"],
  },
  {
    label: "Changan",
    value: "Changan",
    models: [
      "Alsvin",
      "Benni",
      "CS15",
      "CS35",
      "CS55",
      "CS75",
      "Eado",
      "Hunter",
      "Kaicene",
      "Oushang",
      "Raeton",
      "Star 5",
      "Uni-K",
      "Uni-T",
    ],
  },
  {
    label: "Chery",
    value: "Chery",
    models: [
      "Arrizo",
      "Eastar",
      "Exeed",
      "Fulwin",
      "Karry",
      "QQ",
      "Tiggo",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
    ],
  },
  {
    label: "Chevrolet",
    value: "Chevrolet",
    models: [
      "Avalanche",
      "Blazer",
      "Camaro",
      "Caprice",
      "Chevelle",
      "Corvette",
      "Equinox",
      "Impala",
      "Malibu",
      "Monte Carlo",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "Tahoe",
      "Traverse",
      "Trax",
      "Volt",
    ],
  },
  {
    label: "Chrysler",
    value: "Chrysler",
    models: [
      "200",
      "300",
      "300C",
      "300M",
      "Aspen",
      "Cirrus",
      "Concorde",
      "Cordoba",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Pacifica",
      "Prowler",
      "PT Cruiser",
      "Sebring",
      "Voyager",
    ],
  },
  {
    label: "Citroen",
    value: "Citroen",
    models: [
      "Ami",
      "Berlingo",
      "C-Elysee",
      "C3",
      "C4",
      "C5",
      "C5 X",
      "C6",
      "Dispatch",
      "DS 3",
      "DS 4",
      "DS 7",
      "Jumpy",
      "Picasso",
      "Spacetourer",
    ],
  },
  { label: "CMC", value: "CMC", models: ["Veryca"] },
  {
    label: "Dodge",
    value: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Challenger SRT Hellca",
      "Charger",
      "Dakota",
      "Dart",
      "Durango",
      "Durango RT",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stratus",
      "Viper",
    ],
  },
  {
    label: "DongFeng",
    value: "DongFeng",
    models: [
      "A9",
      "AX3",
      "AX5",
      "AX7",
      "Dingo",
      "F12",
      "F5",
      "Fengon",
      "Joyear",
      "K10",
      "M5",
      "Rich",
      "Sokon",
      "V3",
      "Warrior",
    ],
  },
  {
    label: "Exeed",
    value: "Exeed",
    models: ["EOL", "EOL Pro", "GL6", "LSE", "LX", "VX", "VX Plus"],
  },

  {
    label: "Fengon",
    value: "Fengon",
    models: [
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
    ],
  },
  {
    label: "Ferrari",
    value: "Ferrari",
    models: [
      "348",
      "488 Pista",
      "488 Spider",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "Daytona SP3",
      "Dino",
      "F12 Berlinetta",
      "F12 TDF",
      "F8 Spider",
      "F8 Tributo",
      "GTC4Lusso",
      "LaFerrari",
      "LaFerrari Aperta",
      "Monza SP1",
      "Monza SP2",
      "P80/C",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "SP3",
      "Superfast",
    ],
  },

  {
    label: "Fiat",
    value: "Fiat",
    models: [
      "500",
      "500L",
      "500X",
      "Ducato",
      "Panda",
      "Scudo",
      "Talento",
      "Tipo",
    ],
  },
  {
    label: "Ford",
    value: "Ford",
    models: [
      "Bronco",
      "Bronco Sport",
      "C-Max",
      "Edge",
      "Edge Sport",
      "Escape",
      "Everest Hybrid",
      "Explorer",
      "F-150",
      "F-150 Raptor",
      "F-250",
      "F-350",
      "Focus",
      "Fusion",
      "Grand C-Max",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Ranger",
      "Taunus",
      "Taurus",
    ],
  },
  {
    label: "Forthing",
    value: "Forthing",
    models: [
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
    ],
  },
  {
    label: "Foton",
    value: "Foton",
    models: [
      "Aumark",
      "Forland",
      "G9",
      "Gratour",
      "Ollin",
      "Sauvana",
      "Transits",
      "Tunland",
      "View",
      "Weichai",
    ],
  },
  {
    label: "GAC",
    value: "GAC",
    models: [
      "Aion LX",
      "Aion S",
      "Aion V",
      "Arkana",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "Haval F5",
      "Haval F7",
      "Haval H6",
      "Haval H9",
      "Trumpchi GA6",
      "Trumpchi GA8",
      "Trumpchi GS5",
      "Trumpchi M6",
      "ZHONGYI",
    ],
  },
  {
    label: "Geely",
    value: "Geely",
    models: [
      "Aion",
      "Haifeng",
      "Haijie",
      "Jiaji EV",
      "KX3",
      "Lykov EV",
      "Meizu ES6",
      "Meizu ES6 Plus",
      "Meizu EVO",
      "Pionner",
      "Pionner Plus",
      "Vision X50",
      "Xing Rui",
      "Xingyue",
      "Xingyue L",
    ],
  },
  {
    label: "Genesis",
    value: "Genesis",
    models: [
      "Electrified G80",
      "Electrified GV70",
      "G70",
      "G80",
      "G90",
      "GV70",
      "GV80",
    ],
  },
  {
    label: "GMC",
    value: "GMC",
    models: [
      "Acadia",
      "Canyon",
      "Encanto",
      "Envoy",
      "Envoy SLT",
      "Envoy XUV",
      "HUMMER H2",
      "Savana",
      "Sierra",
      "Terrain",
    ],
  },
  {
    label: "Great Wall",
    value: "Great Wall",
    models: [
      "Coolbear",
      "Heimao",
      "Pao",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 7",
    ],
  },
  {
    label: "Haval",
    value: "Haval",
    models: [
      "CUV H",
      "F7 Plus",
      "F7x",
      "H2",
      "H6",
      "H7",
      "H9",
      "H9 LUX",
      "Jolion",
      "Jolion Hybrid",
      "M6",
    ],
  },
  {
    label: "Hino",
    value: "Hino",
    models: ["Hino 300", "Hino 500", "Hino 600", "Hino Dutro"],
  },
  { label: "HiPhi", value: "HiPhi", models: ["HiPhi X", "HiPhi Y", "HiPhi Z"] },
  {
    label: "Honda",
    value: "Honda",
    models: [
      "Accord",
      "Civic",
      "Civic Si",
      "Civic Type R",
      "Clarity",
      "CR-V",
      "Fit",
      "Insight",
      "Passport",
      "Pilot",
      "Ridgeline",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    models: ["E-HS9", "E-QM5", "H5", "H9L", "HS3", "HS5", "HS7", "L5"],
  },
  {
    label: "Hyundai",
    value: "Hyundai",
    models: [
      "Accent",
      "Elantra",
      "Genesis",
      "Ioniq",
      "Kona",
      "Nexo",
      "Palisade",
      "Santa Cruz",
      "Santa Fe",
      "Sonata",
      "Tucson",
      "Veloster",
    ],
  },
  { label: "INEOS", value: "INEOS", models: ["Grenadier"] },
  {
    label: "Infiniti",
    value: "Infiniti",
    models: [
      "Q50",
      "Q60",
      "Q70",
      "Q80",
      "QX30",
      "QX50",
      "QX55",
      "QX60",
      "QX80",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    models: [
      "Amigo",
      "Ascender",
      "D-Max",
      "Elf",
      "F-Series",
      "Impulse",
      "MU-X",
      "N-Series",
      "NPR",
      "P'up",
      "Rodeo",
      "Trooper",
    ],
  },
  {
    label: "Jac",
    value: "Jac",
    models: [
      "J4",
      "J6",
      "J7",
      "Refine S3",
      "Refine S5",
      "S2",
      "S3",
      "S5",
      "S7",
      "T6",
      "T8",
    ],
  },
  {
    label: "Jaguar",
    value: "Jaguar",
    models: [
      "E-Pace",
      "E-Pace R-Dynamic",
      "F-PACE",
      "F-PACE SVR",
      "F-TYPE",
      "F-TYPE R",
      "F-TYPE S",
      "F-TYPE SVR",
      "I-PACE",
      "I-PACE HSE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XF Sportbrake",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK F-TYPE R",
      "XKR",
    ],
  },
  {
    label: "Jeep",
    value: "Jeep",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "Jetour",
    value: "Jetour",
    models: [
      "Cherokee",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Renegade",
      "Wagoneer",
      "Wrangler",
    ],
  },
  {
    label: "JMC",
    value: "JMC",
    models: [
      "Baoda",
      "Carrying",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "Landwind",
      "Teshun",
      "Vigus",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    models: ["E5", "EQ1", "K1", "K2", "K3", "K6", "K7", "S3", "S5", "S7", "S9"],
  },
  {
    label: "Kia",
    value: "Kia",
    models: [
      "Forte",
      "Niro",
      "Optima",
      "Rio",
      "Rondo",
      "Sedona",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
    ],
  },
  {
    label: "Koenigsegg",
    value: "Koenigsegg",
    models: [
      "Agera",
      "CC8S",
      "CCR",
      "CCX",
      "CCX-R",
      "Gemera",
      "Jesko",
      "One:1",
      "Quattroporte",
      "Regera",
    ],
  },
  {
    label: "Lamborghini",
    value: "Lamborghini",
    models: [
      "Asterion",
      "Aventador",
      "Aventador S",
      "Centenario",
      "Countach",
      "Estoque",
      "Gallardo",
      "Gallardo Spyder",
      "Huracan",
      "Huracán",
      "Huracán EVO",
      "Huracán Spyder",
      "Murciélago",
      "Reventón",
      "Sián",
      "Urus",
      "Urus Performante",
    ],
  },
  {
    label: "Land Rover",
    value: "Land Rover",
    models: [
      "Range Rover",
      "Defender",
      "Discovery",
      "Dicovery Sport",
      "Range Rover Sport",
    ],
  },
  {
    label: "Lexus",
    value: "Lexus",
    models: [
      "ES",
      "GS",
      "IS",
      "LC 500",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "UX",
    ],
  },
  {
    label: "Lotus",
    value: "Lotus",
    models: [
      "Carlton",
      "Eclat",
      "Elan",
      "Elise",
      "Elite",
      "Esprit",
      "Europa",
      "Evora",
      "Exige",
      "Seven",
    ],
  },
  { label: "Lucid", value: "Lucid", models: ["Air", "Gravity"] },
  {
    label: "Mahindra",
    value: "Mahindra",
    models: [
      "Alturas G4",
      "Bolero",
      "eKUV100",
      "Furio",
      "KUV100",
      "Marazzo",
      "Pick Up",
      "Scorpio",
      "Scorpio-N",
      "Thar",
      "TUV300",
      "XUV300",
      "XUV700",
      "Xylo",
    ],
  },
  {
    label: "Maserati",
    value: "Maserati",
    models: [
      "Alfieri",
      "Biturbo",
      "Ghibli",
      "GranCabrio",
      "Granturismo",
      "Levante",
      "MC20",
      "Quattroporte",
      "Shamal",
    ],
  },
  {
    label: "Mazda",
    value: "Mazda",
    models: [
      "Mazda CX-3",
      "Mazda CX-30",
      "Mazda CX-5",
      "Mazda CX-50",
      "Mazda CX-9",
      "Mazda MX-5 Miata",
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "MX-5 Miata",
    ],
  },
  {
    label: "McLaren",
    value: "McLaren",
    models: [
      "12C Spider",
      "540C",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "GTR",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
    ],
  },
  {
    label: "Mercedes-Benz",
    value: "Mercedes-Benz",
    models: [
      "A 200",
      "A-Class",
      "AMG CLA-Class",
      "AMG GT",
      "AMG GT Roadster",
      "B-Class",
      "C-Class",
      "CLA",
      "Class S",
      "CLS",
      "E-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQS",
      "G-Class",
      "GLA",
      "GLC",
      "GLC300",
      "GLC350e 4MATIC",
      "GLE",
      "GLS",
      "S-Class",
      "SL",
      "Sprinter",
      "V-Class",
      "X-Class",
    ],
  },
  {
    label: "Mitsubishi",
    value: "Mitsubishi",
    models: [
      "3000GT",
      "ASX",
      "Carisma",
      "Colt",
      "Eclipse",
      "Galant",
      "i-MiEV",
      "Lancer",
      "Montero",
      "Outlander",
      "Pajero",
      "RVR",
      "Shogun",
      "Xpander Cross",
    ],
  },
  {
    label: "Nissan",
    value: "Nissan",
    models: [
      "370Z",
      "370Z Nismo",
      "Altima",
      "Armada",
      "Frontier",
      "GT-R",
      "Juke",
      "Maxima",
      "Murano",
      "Pathfinder",
      "Rogue",
      "Sentra",
      "Titan",
      "Versa",
    ],
  },
  { label: "Peugeot", value: "Peugeot", models: ["3008", "5008"] },
  { label: "Porsche", value: "Porsche", models: ["911", "Cayenne", "Macan"] },
  { label: "RAM", value: "RAM", models: ["1500", "2500"] },
  {
    label: "Renault",
    value: "Renault",
    models: ["Grand Scenic", "Megane", "Talisman"],
  },
  {
    label: "Rolls-Royce",
    value: "Rolls-Royce",
    models: [
      "Corniche",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Spectre",
      "Wraith",
    ],
  },
  {
    label: "Skoda",
    value: "Skoda",
    models: [
      "Citigo-e iV",
      "Enyaq iV",
      "Fabia",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
    ],
  },
  {
    label: "Tesla",
    value: "Tesla",
    models: ["Model S", "Model 3", "Model X", "Model Y"],
  },
  {
    label: "Toyota",
    value: "Toyota",
    models: ["Corolla", "Camry", "RAV4 Adventure", "Supra 191 Edition"],
  },
  {
    label: "Volkswagen",
    value: "Volkswagen",
    models: [
      "Beetle",
      "Bora",
      "Corrado",
      "EOS",
      "Eos CC",
      "Fox",
      "Golf",
      "Golf Estate",
      "Golf GTI",
      "Golf Hatchback",
      "Golf R",
      "Golf SV",
      "ID3",
      "Jetta",
      "Jetta GLI",
      "Passat",
      "Passat CC",
      "Passat Estate",
      "Phaeton",
      "Polo",
      "Rabbit",
      "RNS",
      "Scirocco",
      "Sharan",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  { label: "Volvo", value: "Volvo", models: ["XC90", "S60", "V60"] },
  { label: "Xiaomi", value: "Xiaomi", models: ["SU7"] },
  { label: "Zeekr", value: "Zeekr", models: ["001", "X"] },
];
