export const makes = [
  {
    label: "Abarth",
    value: "Abarth",
    models: ["All", "124", "1999", "595", "695", "F595", "Other"],
  },
  {
    label: "Alfa Romeo",
    value: "Alfa Romeo",
    models: [
      "All",
      "145/146/147",
      "156/159",
      "166",
      "4C",
      "8C",
      "Brera",
      "GIULIETTA",
      "GTV/GT",
      "Giulia",
      "Mito",
      "Spider",
      "Stelvio",
      "Tonale",
      "Other",
    ],
  },
  {
    label: "Aston Martin",
    value: "Aston Martin",
    models: [
      "All",
      "Cygnet",
      "DB10",
      "DB11",
      "DB12",
      "DB7",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Vanquish",
      "Vantage",
      "Virage",
      "Vulcan",
      "Zagato",
      "Other",
    ],
  },
  {
    label: "Audi",
    value: "Audi",
    models: [
      "All",
      "A1",
      "A2",
      "A3",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3 / S-Q3 / RS-Q3",
      " Q5 / S-Q5 / RS-Q5",
      " Q7 / S-Q7",
      " Q8 / S-Q8 / RS-Q8",
      " e-tron / RS e-tron",
      "S3/RS3",
      "S4/RS4",
      "S5/RS5",
      "S6/RS6",
      "S7/RS7",
      "S8",
      "R8",
      "TT",
      "e-tron / RS e-tron",
      "Other",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    models: ["All", "Model 11", "Model 12", "Model 13", "Model 14", "Other"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    models: [
      "All",
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
      "Other",
    ],
  },
  {
    label: "Bentley",
    value: "Bentley",
    models: [
      "All",
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental GT",
      "Flying Spur",
      "Mulsanne",
      "Other",
    ],
  },
  {
    label: "Bestune",
    value: "Bestune",
    models: [
      "All",
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
      "Other",
    ],
  },
  {
    label: "BMW",
    value: "BMW",
    models: [
      "All",
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "i-Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z1",
      "Z3",
      "Z4",
      "Z8",
      "Other",
    ],
  },
  {
    label: "Bugatti",
    value: "Bugatti",
    models: [
      "All",
      "Bolide",
      "Centodieci",
      "Chiron",
      "Divo",
      "EB110",
      "La Finale",
      "La Voiture Noire",
      "Type 251",
      "Type 35",
      "Type 57",
      "Veyron",
      "Other",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    models: [
      "All",
      "ATTO 3",
      "Dolphin",
      "F3",
      "F5",
      "F6",
      "F7",
      "HAN",
      "Leopard",
      "Qin",
      "Seal",
      "Seagul",
      "Sealion",
      "Song",
      "Song L",
      "Song Plus",
      "Song Pro",
      "Tang",
      "Tengshi D9",
      "Yangwang U8",
      "Yuan Plus",
      "Yuan up",
      "E2",
      "Other",
    ],
  },
  {
    label: "Cadillac",
    value: "Cadillac",
    models: [
      "All",
      "ATS",
      "BLS",
      "CT4",
      "CT6",
      "CTS/Catera",
      "DTS/De Ville",
      "Escalade",
      "Fleetwood",
      "Lyriq",
      "SLS",
      "STS/Seville",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTR/Eldorado",
      "XTS",
      "Other",
    ],
  },
  {
    label: "Changan",
    value: "Changan",
    models: [
      "All",
      "Alsvin",
      "Alsvin V7",
      "CS35",
      "CS35 Plus",
      "CS75",
      "CS75 Plus",
      "CS85",
      "CS95",
      "Deepai G318",
      "E Star",
      "Eado",
      "Eado Plus",
      "Lumin",
      "Starlight",
      "UNI-K",
      "Uni-T",
      "Uni-V",
      "Other",
    ],
  },
  {
    label: "Chery",
    value: "Chery",
    models: [
      "All",
      "A11",
      "AIQAR",
      "Arrizo 3",
      "Arizzo 5",
      "Arizzo 7",
      "B11",
      "E5",
      "E8",
      "QQ",
      "S11",
      "Tiggo 3",
      "Tiggo 4",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
      "Tiggo 9",
      "V5",
      "iCar",
      "iCar 03",
      "Other",
    ],
  },
  {
    label: "Chevrolet",
    value: "Chevrolet",
    models: [
      "All",
      "Avalanche",
      "Astro",
      "Apache",
      "Aveo",
      "Bel Air",
      "Blazer",
      "Bolt",
      "CSV",
      "Camaro",
      "Caprice",
      "Captiva",
      "Cavalier",
      "Chevelle",
      "Colorado",
      "Corvette",
      "Cruze",
      "Epica",
      "Equinox",
      "Explorer",
      "Express",
      "Groove",
      "Impala",
      "Lumina",
      "Malibu",
      "Monte Carlo",
      "Nova",
      "Optra",
      "Pickup",
      "SSR",
      "Silverado",
      "Sonic",
      "Spark",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Traverse",
      "Trax",
      "Uplander",
      "Other",
    ],
  },
  {
    label: "Chrysler",
    value: "Chrysler",
    models: [
      "200 / 200C EV",
      "300 / 300C / 300M",
      "Concorde",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Neon",
      "PT Cruiser",
      "Pacifica",
      "Prowler",
      "Sebring",
      "Voyager / Caravan",
      "Other",
    ],
  },
  {
    label: "Citroen",
    value: "Citroen",
    models: [
      "All",
      "AX",
      "Berlingo",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C8",
      "Dispatch",
      "DS 3",
      "DS 4",
      "DS 7",
      "DS 21",
      "Jumper",
      "Saxo",
      "SpaceTourer",
      "Other",
    ],
  },
  {
    label: "CMC",
    value: "CMC",
    models: ["All", "Veryca", "27", "Other"],
  },
  {
    label: "Dodge",
    value: "Dodge",
    models: [
      "All",
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Dakota",
      "Dart",
      "Durango",
      "Grand Caravan",
      "Intrepid",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stratus",
      "Viper",
      "Other",
    ],
  },
  {
    label: "DongFeng",
    value: "DongFeng",
    models: [
      "All",
      "AX7",
      "DFSK V21",
      "DFSK V22",
      "H30 Cross",
      "HUGE",
      "M-Hero 917",
      "Paladin",
      "RICH 7",
      "S30",
      "T5",
      "Other",
    ],
  },
  {
    label: "Exeed",
    value: "Exeed",
    models: [
      "All",
      "EOL",
      "EOL Pro",
      "GL6",
      "LSE",
      "LX",
      "VX",
      "VX Plus",
      "Other",
    ],
  },
  {
    label: "Fengon",
    value: "Fengon",
    models: [
      "All",
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
      "Other",
    ],
  },
  {
    label: "Ferrari",
    value: "Ferrari",
    models: [
      "All",
      "348",
      "488 Pista",
      "488 Spider",
      "812 GTS",
      "812 Superfast",
      "California",
      "California T",
      "Daytona SP3",
      "Dino",
      "F12 Berlinetta",
      "F12 TDF",
      "F8 Spider",
      "F8 Tributo",
      "GTC4Lusso",
      "LaFerrari",
      "LaFerrari Aperta",
      "Monza SP1",
      "Monza SP2",
      "P80/C",
      "Portofino M",
      "Roma",
      "SF90 Spider",
      "SF90 Stradale",
      "SP3",
      "Superfast",
      "Other",
    ],
  },
  {
    label: "Fiat",
    value: "Fiat",
    models: [
      "All",
      "500",
      "500L",
      "500X",
      "124",
      "Ducato",
      "Panda",
      "Scudo",
      "Talento",
      "Tipo",
      "Other",
    ],
  },
  {
    label: "Ford",
    value: "Ford",
    models: [
      "All",
      "Aerostar",
      "Bronco",
      "Crown Victoria",
      "C-Max",
      "Edge",
      "Escape",
      "Everest",
      "Explorer",
      "F-150",
      "F-150 Raptor",
      "F-250",
      "F-350",
      "Focus",
      "Fusion",
      "Grand C-Max",
      "Maverick",
      "Mondeo",
      "Mustang",
      "Ranger",
      "Taunus",
      "Taurus",
      "Other",
    ],
  },
  {
    label: "Forthing",
    value: "Forthing",
    models: [
      "All",
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
      "Other",
    ],
  },
  {
    label: "Foton",
    value: "Foton",
    models: ["All", "SUP", "Tunland", "View", "Other"],
  },
  {
    label: "GAC",
    value: "GAC",
    models: [
      "All",
      "Aion LX",
      "Aion S",
      "Aion V",
      "Arkana",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "Haval F5",
      "Haval F7",
      "Haval H6",
      "Haval H9",
      "Trumpchi GA6",
      "Trumpchi GA8",
      "Trumpchi GS5",
      "Trumpchi M6",
      "ZHONGYI",
      "Other",
    ],
  },
  {
    label: "Geely",
    value: "Geely",
    models: [
      "All",
      "Emgrand",
      "Farizon",
      "Emgrand",
      "Farizon",
      "GCr",
      "GCY",
      "GXr",
      "Geometry C",
      "Monjaro",
      "Okvango",
      "Preface",
      "Starray",
      "Other",
    ],
  },
  {
    label: "Genesis",
    value: "Genesis",
    models: ["All", "G70", "G80", "G90", "GV60", "GV70", "GV80", "Other"],
  },
  {
    label: "GMC",
    value: "GMC",
    models: [
      "All",
      "Acadia",
      "Canyon",
      "Encanto",
      "Envoy",
      "Hummer",
      "Jimmy",
      "Pickup",
      "Suburban",
      "Savana",
      "Sierra",
      "Terrain",
      "Yukon",
      "Other",
    ],
  },
  {
    label: "Great Wall",
    value: "Great Wall",
    models: [
      "All",
      "King Kong",
      "Poer",
      "Wey Gaoshan",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 6",
      "Wingle 7",
      "Other",
    ],
  },
  {
    label: "Haval",
    value: "Haval",
    models: ["All", "Dargo", "H2", "H6", "H8", "H9", "Jolion", "Other"],
  },
  {
    label: "Hino",
    value: "Hino",
    models: ["All"],
  },
  {
    label: "HiPhi",
    value: "HiPhi",
    models: ["All", "X", "Z", "Other"],
  },
  {
    label: "Honda",
    value: "Honda",
    models: [
      "All",
      "Accord",
      "City",
      "Civic",
      "Crider",
      "Crosstour",
      "Clarity",
      "CR-V",
      "ENP1",
      "ENP2",
      "HR-V",
      "Pickup",
      "Fit",
      "Pilot",
      "Odyssey",
      "S2000",
      "Van",
      "Legend",
      "ENS1",
      "Other",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    models: [
      "All",
      "W-HS9",
      "E-QM5",
      "H5",
      "H7",
      "H9",
      "HS5",
      "HS7",
      "HS9",
      "Ousado",
      "Other",
    ],
  },
  {
    label: "Hyundai",
    value: "Hyundai",
    models: [
      "All",
      "Accent",
      "Atos",
      "Avante",
      "Azera",
      "Casper",
      "Centennial",
      "Creta",
      "Elantra",
      "Entourage",
      "Excel",
      "Galloper",
      "Genesis",
      "Getz",
      "Santa Fe",
      "Sonata",
      "Tucson",
      "Veloster",
      "Verna",
      "Veracruz",
      "Venue",
      "Staria",
      "Mighty",
      "Kona",
      "Ioniq",
      "Grand i10",
      "H1",
      "H 100",
      "i10",
      "i20",
      "i30",
      "I40",
      "Other",
    ],
  },
  {
    label: "INEOS",
    value: "INEOS",
    models: ["All"],
  },
  {
    label: "Infiniti",
    value: "Infiniti",
    models: [
      "All",
      "EX35",
      "EX37",
      "FX37",
      "FX45 / FX35",
      "FX50",
      "G-Series",
      "G25",
      "G35",
      "I35 / i30",
      "J30",
      "JX-Series",
      "M-Series",
      "Q30",
      "Q40",
      "Q50",
      "Q60",
      "Q70",
      "QX30",
      "QX4",
      "QX50",
      "QX55",
      "QX60",
      "QX70",
      "QX80",
      "Other",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    models: [
      "All",
      "Amigo",
      "Ascender",
      "D-Max",
      "F-Series",
      "Impulse",
      "MU-X",
      "N-Series",
      "NPR",
      "i-Series",
      "Rodeo",
      "Trooper",
      "Other",
    ],
  },
  {
    label: "Jac",
    value: "Jac",
    models: [
      "All",
      "HK6730",
      "J4",
      "J5",
      "J6",
      "J7",
      "JS4",
      "JS6",
      "M1",
      "M4",
      "M5",
      "S3",
      "S7",
      "T6 Pickup",
      "T8",
      "Other",
    ],
  },
  {
    label: "Jaguar",
    value: "Jaguar",
    models: [
      "All",
      "E-Pace",
      "F-Pace",
      "F-TYPE",
      "I-PACE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK-8",
      "XKR",
      "Other",
    ],
  },
  {
    label: "Jeep",
    value: "Jeep",
    models: [
      "All",
      "Cherokee",
      "Commander",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Grand Wagoneer",
      "Liberty",
      "Patriot",
      "Renegade",
      "Wagoneer",
      "Wrangler",
      "Other",
    ],
  },
  {
    label: "Jetour",
    value: "Jetour",
    models: ["All", "T1", "T2", "X50", "X70", "X90", "X95", "Other"],
  },
  {
    label: "JMC",
    value: "JMC",
    models: [
      "All",
      "Baoda",
      "Carrying",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "Landwind",
      "Teshun",
      "Vigus",
      "Other",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    models: [
      "All",
      "E5",
      "EQ1",
      "K1",
      "K2",
      "K3",
      "K6",
      "K7",
      "S3",
      "S5",
      "S7",
      "S9",
      "Other",
    ],
  },
  {
    label: "Kia",
    value: "Kia",
    models: [
      "All",
      "Bongo",
      "Cadenza",
      "Carens",
      "Carnival",
      "Cerato",
      "Mohave",
      "Niro",
      "Oprius",
      "Optima",
      "Pegas",
      "Picanto",
      "Rio",
      "Rondo",
      "Sedona",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Sephia",
      "Telluride",
      "K3",
      "k5",
      "k8",
      "k9",
      "k900",
      "E75",
      "E76",
      "E79",
      "K900",
      "Other",
    ],
  },
  {
    label: "Koenigsegg",
    value: "Koenigsegg",
    models: [
      "All",
      "Agera",
      "CC8S",
      "CCGT",
      "CCR",
      "CCX",
      "CCX-R",
      "Gemera",
      "Jesko",
      "One:1",
      "Quattroporte",
      "Regera",
      "Other",
    ],
  },
  {
    label: "Lamborghini",
    value: "Lamborghini",
    models: [
      "All",
      "Asterion",
      "Aventador",
      "Centenario",
      "Countach",
      "Estoque",
      "Gallardo",
      "Huracan",
      "Huracán",
      "Murciélago",
      "Reventón",
      "Sián",
      "Urus",
      "Other",
    ],
  },
  {
    label: "Land Rover",
    value: "Land Rover",
    models: [
      "All",
      "Range Rover Vogue",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "LR2",
      "LR3",
      "LR4",
      "Other",
    ],
  },
  {
    label: "Lexus",
    value: "Lexus",
    models: [
      "All",
      "CT Series",
      "ES Series ",
      "GS Series",
      "GX Series",
      "IS Series ",
      "LC 500",
      "LFA",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "SC",
      "UX",
      "Other",
    ],
  },
  {
    label: "Lotus",
    value: "Lotus",
    models: [
      "All",
      "Elan",
      "Eletre",
      "Elise",
      "Emeya",
      "Emira",
      "Esprit",
      "Evora",
      "Exige",
      "Other",
    ],
  },
  {
    label: "Lucid",
    value: "Lucid",
    models: ["All"],
  },
  {
    label: "Mahindra",
    value: "Mahindra",
    models: ["All", "Scorpio Pickup", "XUV 500", "Other"],
  },
  {
    label: "Maserati",
    value: "Maserati",
    models: [
      "All",
      "Alfieri",
      "Ghibli",
      "GranCabrio",
      "Granturismo",
      "Levante",
      "MC20",
      "Quattroporte",
      "Other",
    ],
  },
  {
    label: "Mazda",
    value: "Mazda",
    models: [
      "All",
      "2",
      "3",
      "323",
      "6",
      "626",
      "929",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-7",
      "CX-9",
      "CX-90",
      "MX-5",
      "Pickup",
      "Other",
    ],
  },
  {
    label: "McLaren",
    value: "McLaren",
    models: [
      "All",
      "540C",
      "570GT",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "765LT",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
      "SLR",
      "Other",
    ],
  },
  {
    label: "Mercedes-Benz",
    value: "Mercedes-Benz",
    models: [
      "All",
      "A-Class",
      "B-Class",
      "C-Class",
      "E-Class",
      "G-Class",
      "M-Class",
      "R-Class",
      "S-Class",
      "V-Class",
      "X-Class",
      "CL-Class",
      "CLA",
      "CLC",
      "CLE-Class",
      "CLK-Class",
      "CLS-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQG",
      "EQS",
      "EQV",
      "GL-Class",
      "GLA",
      "GLB",
      "GLC",
      "GLE-Class",
      "GLK-Class",
      "GLS-Class",
      "GT",
      "GLC Coupe",
      "S580e",
      "SEC-Class",
      "SEL-Class",
      "SL-Class",
      "SLC",
      "SLS",
      "Sprinter",
      "Viano",
      "Vito",
      "Other",
    ],
  },
  {
    label: "Mitsubishi",
    value: "Mitsubishi",
    models: [
      "All",
      "ASX",
      "Attrage",
      "Colt",
      "Eclipse",
      "Cruse",
      "Galant",
      "i-MiEV",
      "Lancer",
      "Montero",
      "Mirage",
      "Outlander",
      "Pajero",
      "Xpander",
      "Evolution",
      "3000GT",
      "Canter",
      "Fortis",
      "L200",
      "Van",
      "Other",
    ],
  },
  {
    label: "Mini",
    value: "Mini",
    models: [
      "All",
      "Clubman",
      "Cooper",
      "Cooper Clubman",
      "Countryman",
      "Coupe",
      "Mayfair",
      "Paceman",
      "Roadster",
      "Other",
    ],
  },
  {
    label: "Nissan",
    value: "Nissan",
    models: [
      "All",
      "Altima",
      "Armada",
      "Sunny",
      "X-Trail",
      "Kicks",
      "Sentra",
      "Pathfinder",
      "Patrol",
      "GT-R",
      "Xterra",
      "Navara",
      "370Z",
      "Juke",
      "Murano",
      "Qashqai",
      "Quest",
      "Rogue",
      "Maxima",
      "Pickup",
      "Micra",
      "Teana",
      "Leaf",
      "Fuga",
      "NV350",
      "NV200",
      "Frontier",
      "Skyline",
      "Titan",
      "Van",
      "Other",
    ],
  },
  {
    label: "Peugeot",
    value: "Peugeot",
    models: [
      "All",
      "108",
      "207",
      "208",
      "301",
      "307",
      "308",
      "407",
      "408",
      "504",
      "508",
      "607",
      "2008",
      "3008",
      "5008",
      "Expert",
      "Rifter",
      "Partner",
      "Traveller",
      "Boxer",
      "Other",
    ],
  },
  {
    label: "Porsche",
    value: "Porsche",
    models: [
      "All",
      "911",
      "Taycan",
      "Macan",
      "Cayenne",
      "Boxster",
      "Cayman",
      "Panamera",
      "918",
      "928",
      "718",
      "Other",
    ],
  },
  {
    label: "RAM",
    value: "RAM",
    models: [
      "All",
      "1500",
      "1500 Classic",
      "1500 TRX",
      "2500",
      "Warlock",
      "Other",
    ],
  },
  {
    label: "Renault",
    value: "Renault",
    models: [
      "All",
      "Arkana",
      "Captur",
      "Clio",
      "Dokker",
      "Duster",
      "Espace",
      "Express Van",
      "Fluence",
      "Koleos",
      "Laguna",
      "Logan",
      "Master",
      "Megane",
      "Symbol",
      "Tailsman",
      "Trafic",
      "Twingo",
      "Master",
      "Twizy",
      "Zoe",
      "Tailsman",
      "Other",
    ],
  },
  {
    label: "Rolls-Royce",
    value: "Rolls-Royce",
    models: [
      "All",
      "Cullinan",
      "Dawn",
      "Ghost",
      "Phantom",
      "Silver Spur",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Spectre",
      "Wraith",
      "Other",
    ],
  },
  {
    label: "Skoda",
    value: "Skoda",
    models: [
      "All",
      "Fabia",
      "Kamiq",
      "Kodiaq",
      "Kushak",
      "Octavia",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yati",
      "Other",
    ],
  },
  {
    label: "Tesla",
    value: "Tesla",
    models: ["All", "Model S", "Model 3", "Model X", "Model Y", "Other"],
  },
  {
    label: "Toyota",
    value: "Toyota",
    models: [
      "All",
      "4Runner",
      "86",
      "Alphard",
      "Aurion",
      "Avalon",
      "Avanza",
      "Avensis",
      "BZ4X",
      "C-HR",
      "Camry",
      "Celica",
      "Coaster",
      "Corolla",
      "Corona",
      "Cressida",
      "Crown",
      "Echo",
      "FJ Cruiser",
      "Fortuner",
      "Frontlander",
      "GR86",
      "Granvia",
      "Hiace",
      "Highlander",
      "Hilux",
      "IQ",
      "Innova",
      "Land Cruiser",
      "Levin",
      "MR2",
      "Mirai",
      "Pickup",
      "Prado",
      "Previa",
      "Prius",
      "Raise",
      "Rav 4",
      "Rumion",
      "Rush",
      "Scion",
      "Sequoia",
      "Sienna",
      "Supra",
      "Tacoma",
      "Tercel",
      "Tundra",
      "Urban Cruiser",
      "Veloz",
      "Venza",
      "Vitz",
      "Wigo",
      "XA",
      "Yaris",
      "Zelas",
      "bZ3",
      "iA",
      "Other",
    ],
  },
  {
    label: "Volkswagen",
    value: "Volkswagen",
    models: [
      "All",
      "Arteon",
      "Atlas",
      "Beetle",
      "Bora",
      "Corrado",
      "Caddy",
      "Crafter",
      "E-Lavida",
      "EOS",
      "Eurovan",
      "GTI",
      "Golf",
      "ID.3",
      "ID.4",
      "ID.6",
      "ID.7",
      "Jetta",
      "Multivan",
      "Phaeton",
      "Polo",
      "Routan",
      "Scirocco",
      "Sharan",
      "T-Roc",
      "Tayron",
      "Teramont",
      "Tiguan",
      "Touareg",
      "Transporter",
      "Vento",
      "Viloran",
      "Other",
    ],
  },
  {
    label: "Volvo",
    value: "Volvo",
    models: [
      "All",
      "C-Class",
      "C40",
      "S-Class",
      "S90",
      "V-Class",
      "V90",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC70",
      "XC90",
      "Other",
    ],
  },
  {
    label: "Xiaomi",
    value: "Xiaomi",
    models: ["All"],
  },
  {
    label: "Zeekr",
    value: "Zeekr",
    models: ["All", "001", "007", "009", "X", "Other"],
  },
];

export const arabicMakes = [
  {
    label: "أبارث",
    value: "أبارث",
    enValue: "Abarth",
    models: ["الكل", "124", "1999", "595", "695", "595 اف", "آخرى"],
  },

  {
    label: "ألفا روميو",
    value: "ألفا روميو",
    enValue: "Alfa Romeo",
    models: [
      "الكل",
      "145/146/147",
      "159/156",
      "166",
      "سي4",
      "سي8",
      "بريرا",
      "GIULIETTA",
      "GTV/GT",
      "Giulia",
      "Mito",
      "Spider",
      "Stelvio",
      "Tonale",
      "آخرى",
    ],
  },
  {
    label: "أستون مارتن",
    value: "أستون مارتن",
    enValue: "Aston Martin",
    models: [
      "الكل",
      "Cygnet",
      "DB10",
      "DB11",
      "DB12",
      "DB7",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "One-77",
      "Rapide",
      "Vanquish",
      "Vantage",
      "Virage",
      "Vulcan",
      "Zagato",
      "Other",
      "آخرى",
    ],
  },
  {
    label: "أودي",
    value: "أودي",
    enValue: "Audi",
    models: [
      "الكل",
      "A1",
      "A2",
      "A3",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3 / S-Q3 / RS-Q3",
      " Q5 / S-Q5 / RS-Q5",
      " Q7 / S-Q7",
      " Q8 / S-Q8 / RS-Q8",
      " e-tron / RS e-tron",
      "S3/RS3",
      "S4/RS4",
      "S5/RS5",
      "S6/RS6",
      "S7/RS7",
      "S8",
      "R8",
      "TT",
      "e-tron / RS e-tron",
      "آخرى",
    ],
  },
  {
    label: "Avatr",
    value: "Avatr",
    enValue: "Avatr",
    models: ["الكل", "Model 11", "Model 12", "Model 13", "Model 14", "آخرى"],
  },
  {
    label: "BAIC",
    value: "BAIC",
    enValue: "BAIC",
    models: [
      "الكل",
      "A60",
      "A70",
      "AB180",
      "B20e",
      "B20EV",
      "B30",
      "B30e",
      "B30EV",
      "B30W",
      "BX270",
      "BX335",
      "BX350",
      "EX200",
      "EX260",
      "GS5",
      "H530",
      "HX5",
      "Jiang ling Yushen B90",
      "M30",
      "MF303",
      "MF306",
      "MF310",
      "U5",
      "X35",
      "X50",
      "آخرى",
    ],
  },
  {
    label: "بنتلى",
    value: "بنتلى",
    enValue: "Bentley",
    models: [
      "الكل",
      "أرنـاج",
      "أزور",
      "بنتايغا",
      "بروك لاندز",
      "كونتينينتال",
      "كونتينينتال جي تي",
      "فلاينغ سبير",
      "مالسان",
      "آخرى",
    ],
  },
  {
    label: "بيستون",
    value: "بيستون",
    enValue: "Bestune",
    models: [
      "الكل",
      "B70",
      "B90",
      "C50",
      "C60",
      "M60",
      "T30",
      "T70",
      "T77",
      "T90",
      "T99",
      "X40",
      "آخرى",
    ],
  },
  {
    label: "بي ام دبليو",
    value: "بي ام دبليو",
    enValue: "BMW",
    models: [
      "الكل",
      "1 الفئة",
      "2 الفئة",
      "3 الفئة",
      "4 الفئة",
      "5 الفئة",
      "6 الفئة",
      "7 الفئة",
      "8 الفئة",
      "i الفئة",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z1",
      "Z3",
      "Z4",
      "Z8",
      "آخرى",
    ],
  },
  {
    label: "بوغاتي",
    value: "بوغاتي",
    enValue: "Bugatti",
    models: [
      "الكل",
      "بُلَيْد",
      "سنتوديتشي",
      "شيرون",
      "ديفو",
      "110 إي بي",
      "لا فينال",
      "لا فواتور نوار",
      "251 تايب",
      "35تايب",
      "57 تايب",
      "فيرون",
      "آخرى",
    ],
  },
  {
    label: "BYD",
    value: "BYD",
    enValue: "BYD",
    models: [
      "الكل",
      "ATTO 3",
      "Dolphin",
      "F3",
      "F5",
      "F6",
      "F7",
      "HAN",
      "Leopard",
      "Qin",
      "Seal",
      "Seagul",
      "Sealion",
      "Song",
      "Song L",
      "Song Plus",
      "Song Pro",
      "Tang",
      "Tengshi D9",
      "Yangwang U8",
      "Yuan Plus",
      "Yuan up",
      "E2",
      "آخرى",
    ],
  },
  {
    label: "كاديلاك",
    value: "كاديلاك",
    enValue: "Cadillac",
    models: [
      "الكل",
      "ATS",
      "BLS",
      "CT4",
      "CT6",
      "CTS/Catera",
      "DTS/De Ville",
      "إسكاليد",
      "Fleetwood",
      "Lyriq",
      "SLS",
      "STS/Seville",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "XTR/Eldorado",
      "XTS",
      "آخرى",
    ],
  },
  {
    label: "شانجان",
    value: "شانجان",
    enValue: "Changan",
    models: [
      "الكل",
      "Alsvin",
      "Alsvin V7",
      "CS35",
      "CS35 Plus",
      "CS75",
      "CS75 Plus",
      "CS85",
      "CS95",
      "Deepai G318",
      "E Star",
      "Eado",
      "Eado Plus",
      "Lumin",
      "Starlight",
      "UNI-K",
      "Uni-T",
      "Uni-V",
      "آخرى",
    ],
  },
  {
    label: "شيري",
    value: "شيري",
    enValue: "Chery",
    models: [
      "الكل",
      "A11",
      "AIQAR",
      "Arrizo 3",
      "Arizzo 5",
      "Arizzo 7",
      "B11",
      "E5",
      "E8",
      "QQ",
      "S11",
      "Tiggo 3",
      "Tiggo 4",
      "Tiggo 5",
      "Tiggo 7",
      "Tiggo 8",
      "Tiggo 9",
      "V5",
      "iCar",
      "iCar 03",
      "آخرى",
    ],
  },
  {
    label: "شيفروليه",
    value: "شيفروليه",
    enValue: "Chevrolet",
    models: [
      "الكل",
      "افالانش",
      "أسترو",
      "أباتشي",
      "أفيو",
      "Bel Air",
      "بليزر",
      "بولت",
      "CSV",
      "كامارو",
      "كابريس",
      "كابتيفا",
      "كافالير",
      "شيفيل",
      "كولورادو",
      "كورفيت",
      "كروز",
      "ابيكا",
      "ايكونس",
      "اكسبلورر",
      "اكسبرس",
      "غرووف",
      "إمبالا",
      "لومينا",
      "ماليبو",
      "مونت كارلو",
      "نوفا",
      "أوبترا",
      "بيك اب",
      "SSR",
      "سيلفرادو",
      "سونيك",
      "سبارك",
      "سوبربان",
      "تاهو",
      "تريل بليزر",
      "ترافيرس",
      "تراكس",
      "أبلاندر",
      "آخرى",
    ],
  },
  {
    label: "كرايسلر",
    value: "كرايسلر",
    enValue: "Chrysler",
    models: [
      "الكل",
      "200 / 200C EV",
      "300 / 300C / 300M",
      "Concorde",
      "Crossfire",
      "Imperial",
      "Lancer",
      "Le Baron",
      "LHS",
      "New Yorker",
      "Newport",
      "Neon",
      "PT Cruiser",
      "Pacifica",
      "Prowler",
      "Sebring",
      "Voyager / Caravan",
      "آخرى",
    ],
  },
  {
    label: "سيتروين",
    value: "سيتروين",
    enValue: "Citroën",
    models: [
      "الكل",
      "AX",
      "بيرلينغو",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C8",
      "ديسباتش",
      "DS 3",
      "DS 4",
      "DS 7",
      "DS 21",
      "Jumper",
      "Saxo",
      "SpaceTourer",
      "آخرى",
    ],
  },
  {
    label: "CMC",
    value: "CMC",
    enValue: "CMC",
    models: ["الكل", "Veryca", "27", "آخرى"],
  },
  {
    label: "دودج",
    value: "دودج",
    enValue: "Dodge",
    models: [
      "الكل",
      "أفينجر",
      "كاليبر",
      "تشالنجر",
      "تشارجر",
      "Dakota",
      "دارت",
      "دورانغو",
      "غراند كارافان",
      "إنتريبيد",
      "جورنّي",
      "ماغنوم",
      "نيون",
      "نيترو",
      "رام",
      "ستراتوس",
      "فيبر",
      "آخرى",
    ],
  },
  {
    label: "دونغفنغ",
    value: "دونغفنغ",
    enValue: "Dongfeng",
    models: [
      "الكل",
      "A9",
      "AX3",
      "AX5",
      "AX7",
      "دنجو",
      "F12",
      "F5",
      "فنجون",
      "جويير",
      "K10",
      "M5",
      "ريتش",
      "سوكون",
      "V3",
      "ووريور",
      "آخرى",
    ],
  },
  {
    label: "إكسيد",
    value: "إكسيد",
    enValue: "Exeed",
    models: [
      "الكل",
      "EOL",
      "EOL Pro",
      "GL6",
      "LSE",
      "LX",
      "VX",
      "VX Plus",
      "آخرى",
    ],
  },

  {
    label: "فينغون",
    value: "فينغون",
    enValue: "Fengon",
    models: [
      "الكل",
      "360",
      "360 Cross",
      "380",
      "430",
      "530",
      "560",
      "580",
      "E1",
      "IX5",
      "IX7",
      "T5",
      "آخرى",
    ],
  },
  {
    label: "فيراري",
    value: "فيراري",
    enValue: "Ferrari",
    models: [
      "الكل",
      "348",
      "488 بيستا",
      "488 سبايدر",
      "812 GTS",
      "812 سوبر فاست",
      "كاليفورنيا",
      "كاليفورنيا تي",
      "دايتونا SP3",
      "دينو",
      "إف 12 برلينيتا",
      "F12 TDF",
      "F8 سبايدر",
      "إف 8 تريبيوتو",
      "جي تي سي 4 لوسو",
      "لافيراري",
      "لافيراري أبيرتا",
      "مونزا SP1",
      "مونزا SP2",
      "P80/C",
      "بورتوفينو إم",
      "روما",
      "SF90 سبايدر",
      "SF90 سترادالي",
      "SP3",
      "سوبر فاست",
      "آخرى",
    ],
  },

  {
    label: "فيات",
    value: "فيات",
    enValue: "Fiat",
    models: [
      "الكل",
      "500",
      "500L",
      "500X",
      "124",
      "دوكاتو",
      "باندا",
      "سكودو",
      "تالينتو",
      "تيبو",
      "آخرى",
    ],
  },
  {
    label: "فورد",
    value: "فورد",
    enValue: "Ford",
    models: [
      "الكل",
      "برونكو",
      "سي-ماكس",
      "إدج",
      "إسكيب",
      "إيفرست",
      "إكسبلورر",
      "إف-150",
      "إف-150 رابتور",
      "إف-250",
      "إف-350",
      "فوكاس",
      "فيوجن",
      "جراند سي-ماكس",
      "مافريك",
      "مونديو",
      "موستانغ",
      "رينجر",
      "تاونوس",
      "توريز",
      "آخرى",
    ],
  },
  {
    label: "فورثينغ",
    value: "فورثينغ",
    enValue: "Forthing",
    models: [
      "الكل",
      "E300",
      "E400",
      "M200",
      "T3 EV",
      "T5 EV",
      "T5 Plus",
      "T5 Pro",
      "T9",
      "آخرى",
    ],
  },
  {
    label: "فوتون",
    value: "فوتون",
    enValue: "Foton",
    models: ["الكل", "SUP", "Tunland", "View", "آخرى", "توريز"],
  },
  {
    label: "جي أي سي",
    value: "جي أي سي",
    enValue: "GAC",
    models: [
      "الكل",
      "أيون LX",
      "أيون S",
      "أيون V",
      "أركانا",
      "GAC-EV",
      "GAC-R",
      "GE3",
      "GN8",
      "GS3",
      "GS4",
      "GS8",
      "هافال F5",
      "هافال F7",
      "هافال H6",
      "هافال H9",
      "ترمبشي GA6",
      "ترمبشي GA8",
      "ترمبشي GS5",
      "ترمبشي M6",
      "ZHONGYI",
      "آخرى",
    ],
  },
  {
    label: "جيلي",
    value: "جيلي",
    enValue: "Geely",
    models: [
      "الكل",
      "Emgrand",
      "Farizon",
      "Emgrand",
      "Farizon",
      "GCr",
      "GCY",
      "GXr",
      "Geometry C",
      "Monjaro",
      "Okvango",
      "Preface",
      "Starray",
      "آخرى",
    ],
  },
  {
    label: "جيسنيسيس",
    value: "جيسنيسيس",
    enValue: "Genesis",
    models: [
      "الكل",
      "كوبيه",
      "G70",
      "G80",
      "G90",
      "GV60",
      "GV70",
      "GV80",
      "آخرى",
    ],
  },
  {
    label: "جي إم سي",
    value: "جي إم سي",
    enValue: "GMC",
    models: [
      "الكل",
      "أكاديا",
      "كانيون",
      "إنكانتوا",
      "همر",
      "جيمي",
      "بيك اب",
      "سوبربان",
      "سافانا",
      "سييرا",
      "تيراين",
      "يوكون",
      "آخرى",
    ],
  },
  {
    label: "جريت وول",
    value: "جريت وول",
    enValue: "Great Wall",
    models: [
      "الكل",
      "King Kong",
      "Poer",
      "Wey Gaoshan",
      "Steed",
      "Voleex C10",
      "Voleex C30",
      "Wingle 5",
      "Wingle 6",
      "Wingle 7",
      "آخرى",
    ],
  },
  {
    label: "هافال",
    value: "هافال",
    enValue: "Haval",
    models: ["الكل", "Dargo", "H2", "H6", "H8", "H9", "Jolion", "آخرى"],
  },
  {
    label: "هينو",
    value: "هينو",
    enValue: "Hino",
    models: ["All"],
  },
  {
    label: "HiPhi",
    value: "HiPhi",
    enValue: "HiPhi",
    models: ["All", "X", "Z", "Other"],
  },
  {
    label: "هوندا",
    value: "هوندا",
    enValue: "Honda",
    models: [
      "الكل",
      "أكورد",
      "سيتي",
      "سيفيك",
      "Crider",
      "Crosstour",
      "Clarity",
      "CR-V",
      "ENP1",
      "ENP2",
      "HR-V",
      "بيك آب",
      "Fit",
      "بايلوت",
      "اوديسي",
      "S2000",
      "فان",
      "ليجند",
      "ENS1",
      "آخرى",
    ],
  },
  {
    label: "Hongqi",
    value: "Hongqi",
    enValue: "Hongqi",
    models: [
      "الكل",
      "W-HS9",
      "E-QM5",
      "H5",
      "H7",
      "H9",
      "HS5",
      "HS7",
      "HS9",
      "Ousado",
      "آخرى",
    ],
  },
  {
    label: "هيونداي",
    value: "هيونداي",
    enValue: "Hyundai",
    models: [
      "أكسنت",
      "اتوس",
      "افانتي",
      "ازيرا",
      "كاسبر",
      "سينتينتال",
      "كوبيه",
      "كريتا",
      "ألنترا",
      "انتوراج",
      "اكسيل",
      "جالوبر",
      "جينيسيس",
      "غيتز",
      "سانتا فيه",
      "سوناتا",
      "توكسون",
      "فولستر",
      "فيرنا",
      "فيراكروزر",
      "فينيو",
      "ستاريا",
      "مايتي",
      "كونا",
      "ايونيك",
      "10جراند أي",
      "H1",
      "H100",
      "i10",
      "i20",
      "i30",
      "i40",
      "i40",
      "i40",
      "i40",
      "آخرى",
    ],
  },
  {
    label: "INEOS",
    value: "INEOS",
    enValue: "INEOS",
    models: ["الكل"],
  },
  {
    label: "إنفينيتي",
    value: "إنفينيتي",
    enValue: "Infiniti",
    models: [
      "الكل",
      "Q50",
      "Q60",
      "Q70",
      "Q80",
      "QX30",
      "QX50",
      "QX55",
      "QX60",
      "QX80",
      "آخرى",
    ],
  },
  {
    label: "Isuzu",
    value: "Isuzu",
    enValue: "Isuzu",
    models: [
      "الكل",
      "اميغو",
      "أسندر",
      "D-Max",
      "F-سلسلة",
      "Impulse",
      "MU-X",
      "N-سلسلة",
      "NPR",
      "i-سلسلة",
      "روديو",
      "تروبر",
      "آخرى",
    ],
  },
  {
    label: "جاك",
    value: "جاك",
    enValue: "JAC",
    models: [
      "الكل",
      "HK6730",
      "J4",
      "J5",
      "J6",
      "J7",
      "JS4",
      "JS6",
      "M1",
      "M4",
      "M5",
      "S3",
      "S7",
      "T6 Pickup",
      "T8",
      "آخرى",
    ],
  },
  {
    label: "جاكوار",
    value: "جاكوار",
    enValue: "Jaguar",
    models: [
      "الكل",
      "E-Pace",
      "F-Pace",
      "F-TYPE",
      "I-PACE",
      "S-TYPE",
      "X-TYPE",
      "XE",
      "XF",
      "XFR-S",
      "XJ",
      "XJ L",
      "XK",
      "XK-8",
      "XKR",
      "آخرى",
    ],
  },
  {
    label: "جيب",
    value: "جيب",
    enValue: "Jeep",
    models: [
      "الكل",
      "شيروكي",
      "كوماندر",
      "كومباس",
      "غلادياتور",
      "جراند شيروكي",
      "غراند واغونيير",
      "باتريوت",
      "ليبرتي",
      "رينيغيد",
      "واغونيير",
      "رانجلر",
    ],
  },
  {
    label: "جيتور",
    value: "جيتور",
    enValue: "Jietu",
    models: ["الكل", "T1", "T2", "X50", "X70", "X90", "X95", "آخرى"],
  },
  {
    label: "JMC",
    value: "JMC",
    enValue: "JMC",
    models: [
      "الكل",
      "باودا",
      "كارينغ",
      "G5",
      "JX100",
      "JX200",
      "JX300",
      "JX4",
      "لاند ويند",
      "تيسون",
      "فيغوس",
      "آخرى",
    ],
  },
  {
    label: "Kaiya",
    value: "Kaiya",
    enValue: "Kaiya",
    models: ["E5", "EQ1", "K1", "K2", "K3", "K6", "K7", "S3", "S5", "S7", "S9"],
  },
  {
    label: "كيا",
    value: "كيا",
    enValue: "Kia",
    models: [
      "الكل",
      "بونجو",
      "كادينزا",
      "كارينز",
      "كرنفال",
      "سيراتو",
      "موهاف",
      "نيرو",
      "اوبريوس",
      "أوبتيما",
      "بيجاس",
      "بيكانتو",
      "ريو",
      "روندو",
      "سيدونا",
      "سورنتو",
      "سول",
      "سبورتاج",
      "ستينجر",
      "سيفيا",
      "تيلورايد",
      "K3",
      "k5",
      "k8",
      "k9",
      "k900",
      "E75",
      "E76",
      "E79",
      "k900",
      "آخرى",
    ],
  },
  {
    label: "كوينيجسيج",
    value: "كوينيجسيج",
    enValue: "Koenigsegg",
    models: [
      "الكل",
      "أغيرا",
      "CC8S",
      "CC8S",
      "CCGT",
      "CCR",
      "CCX",
      "CCX-R",
      "جيميرا",
      "جيسكو",
      "One:1",
      "كواتروبورتي",
      "ريجيرا",
      "آخرى",
    ],
  },
  {
    label: "لامبورغيني",
    value: "لامبورغيني",
    enValue: "Lamborghini",
    models: [
      "الكل",
      "Asterion",
      "آڤنتادور",
      "سنترينو",
      "كونتاش",
      "إستوك",
      "گالاردو",
      "هوراكان",
      "مرشيلاغو",
      "ريفينتون",
      "سيان",
      "أوروس",
      "آخرى",
    ],
  },
  {
    label: "لاند روفر / رانج روفر",
    value: "لاند روفر / رانج روفر",
    enValue: "Land Rover",
    models: [
      "الكل",
      "رانج روفر فوج",
      "رانج روفر إيفوك",
      "رانج روفر سبورت",
      "رانج روفر فيلار",
      "ديفندر",
      "ديسكفري",
      "ديسكفري سبورت",
      "فريلاندر",
      "LR2",
      "LR3",
      "LR4",
      "آخرى",
    ],
  },
  {
    label: "لكزس",
    value: "لكزس",
    enValue: "Lexus",
    models: [
      "الكل",
      "CT فئة",
      "ESفئة",
      "GSفئة",
      "GX فئة",
      "ISفئة",
      "LC 500",
      "LFA",
      "LS",
      "LX",
      "NS",
      "RC",
      "RX",
      "RZ",
      "SC",
      "UX",
      "آخرى",
    ],
  },
  {
    label: "لوتس",
    value: "لوتس",
    enValue: "Lotus",
    models: [
      "الكل",
      "Elan",
      "Eletre",
      "Elise",
      "Emeya",
      "Emira",
      "Esprit",
      "Evora",
      "Exige",
      "آخرى",
    ],
  },
  {
    label: "لوسيد",
    value: "لوسيد",
    enValue: "Lucid",
    models: ["الكل"],
  },
  {
    label: "ماهيندرا",
    value: "ماهيندرا",
    enValue: "Mahindra",
    models: [
      "الكل",
      "ألتوراس G4",
      "بوليرو",
      "eKUV100",
      "فوريوا",
      "KUV100",
      "مارازو",
      "بيك أب",
      "سكورتب",
      "سكورتب-N",
      "ثار",
      "TUV300",
      "XUV300",
      "XUV700",
      "زيليو",
      "آخرى",
    ],
  },
  {
    label: "مازيراتي",
    value: "مازيراتي",
    enValue: "Maserati",
    models: [
      "الكل",
      "ألفييري",
      "غيبلي",
      "غراند كابريو",
      "غراند توريسمو",
      "ليفانتي",
      "إم سي 20",
      "كواتروبورتي",
      "آخرى",
    ],
  },
  {
    label: "مازدا",
    value: "مازدا",
    enValue: "Mazda",
    models: [
      "الكل",
      "2",
      "3",
      "323",
      "6",
      "626",
      "929",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-7",
      "CX-9",
      "CX-90",
      "MX-5",
      "بيك اب",
      "آخرى",
    ],
  },
  {
    label: "ماكلارين",
    value: "ماكلارين",
    enValue: "McLaren",
    models: [
      "الكل",
      "540C",
      "570GT",
      "570S",
      "600LT",
      "650S",
      "675LT",
      "720S",
      "765LT",
      "Artura",
      "Elva",
      "F1",
      "GT",
      "MP4-12C",
      "MP4-650S",
      "MP4-720S",
      "P1",
      "P1 GTR",
      "Sabre",
      "Senna",
      "Speedtail",
      "SLR",
      "آخرى",
    ],
  },
  {
    label: "مرسيدس بنز",
    value: "مرسيدس بنز",
    enValue: "Mercedes-Benz",
    models: [
      "الكل",
      "A-فــئة",
      "B-فــئة",
      "C-فــئة",
      "E-فــئة",
      "G-فــئة",
      "M-فــئة",
      "R-فــئة",
      "S-فــئة",
      "V-فــئة",
      "X-فــئة",
      "CL-فئة",
      "CLA",
      "CLC",
      "CLE-فئة",
      "CLK-فئة",
      "CLS-فئة",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQG",
      "EQS",
      "EQV",
      "GL-فئة",
      "GLA",
      "GLB",
      "GLC",
      "GLE ",
      "GLK ",
      "GLS ",
      "GT",
      "S580e",
      "SEC-Class",
      "SEL-Class",
      "SL-Class",
      "SLC",
      "SLS",
      "Sprinter",
      "Viano",
      "Vito",
      "آخرى",
    ],
  },
  {
    label: "ميتسوبيشي",
    value: "ميتسوبيشي",
    enValue: "Mitsubishi",
    models: [
      "الكل",
      "ASX",
      "اتراج",
      "كولت",
      "اكلبس",
      "اكلبس كروز",
      "جالانت",
      "i-MiEV",
      "لانسر",
      "مونتيرو",
      "ميراج",
      "أوتلاندر",
      "باجيرو",
      "اكسباندر",
      "ابفوليوشن",
      "3000GT",
      "Canter",
      "فورتس",
      "L200",
      "Van",
      "آخرى",
    ],
  },
  {
    label: "Mini",
    value: "Mini",
    enValue: "Mini",
    models: [
      "الكل",
      "كلوبمان",
      "كوبر",
      "كوبر كلوبمان",
      "كنتري مان",
      "كوبيه",
      "مايفير",
      "بيسمان",
      "رودستر",
      "آخرى",
    ],
  },
  {
    label: "نيسان",
    value: "نيسان",
    enValue: "Nissan",
    models: [
      "الكل",
      "ألتيما",
      "ارمادا",
      "صني",
      "إكس تريل",
      "كيكس",
      "سينترا",
      "باثفايندر",
      "باترول",
      "جي تي-آر",
      "إكس تيرا",
      "نافارا",
      "370Z",
      "جوك",
      "مورانو",
      "قاشقاي",
      "كوست",
      "روج",
      "ماكسيما",
      "بيك اب",
      "مايكرا",
      "تينا",
      "ليف",
      "فوجا",
      "NV350",
      "NV200",
      "فرونتير",
      "سكاي لاين",
      "تيتان",
      "فان",
      "آخرى",
    ],
  },
  {
    label: "بيجو",
    value: "بيجو",
    enValue: "Peugeot",
    models: [
      "الكل",
      "108",
      "207",
      "208",
      "301",
      "307",
      "308",
      "407",
      "408",
      "504",
      "508",
      "607",
      "2008",
      "3008",
      "5008",
      "اكسبرت",
      "ريفتر",
      "بارتنر",
      "ترافلر",
      "بوكسر",
      "آخرى",
    ],
  },
  {
    label: "بورشه",
    value: "بورشه",
    enValue: "Porsche",
    models: [
      "الكل",
      "911",
      "تايكان",
      "ماكان",
      "كايين",
      "بوكستر",
      "كايمان",
      "باناميرا",
      "918",
      "928",
      "718",
      "آخرى",
    ],
  },
  {
    label: "رام",
    value: "رام",
    enValue: "Ram",
    models: [
      "All",
      "1500",
      "1500 Classic",
      "1500 TRX",
      "2500",
      "Warlock",
      "Other",
    ],
  },
  {
    label: "رينو",
    value: "رينو",
    enValue: "Renault",
    models: [
      "الكل",
      "الجميع",
      "Arkana",
      "Captur",
      "كليو",
      "دوكر",
      "داستر",
      "ايسكيب",
      "فان اكسبرس",
      "Fluence",
      "كوليوس",
      "Laguna",
      "لوغان",
      "ماستر",
      "ميغان",
      "سيمبول",
      "Tailsman",
      "Trafic",
      "توينغو",
      "ماستر",
      "تويزي",
      "زوي",
      "Tailsman",
      "آخرى",
    ],
  },
  {
    label: "رولز رويس",
    value: "رولز رويس",
    enValue: "Rolls Royce",
    models: [
      "الكل",
      "كولينان",
      "داون",
      "غوست",
      "فانتوم",
      "سيلفر سبير",
      "سيلفر كلاود",
      "سيلفر داون",
      "سيلفر سيراف",
      "سيلفر شادو",
      "سيلفر سبيريت",
      "سبكتر",
      "رايث",
      "آخرى",
    ],
  },
  {
    label: "سكودا",
    value: "سكودا",
    enValue: "Skoda",
    models: [
      "الكل",
      "فابيا",
      "كاميك",
      "كاروك",
      "كودياك",
      "كوشاك",
      "أوكتافيا",
      "رابيد",
      "رومستر",
      "سكالا",
      "سوبيرب",
      "ياتي",
      "آخرى",
    ],
  },
  {
    label: "تسلا",
    value: "تسلا",
    enValue: "Tesla",
    models: ["All", "Model S", "Model 3", "Model X", "Model Y", "Other"],
  },
  {
    label: "تويوتا",
    value: "تويوتا",
    enValue: "Toyota",
    models: [
      "الكل",
      "4رانر",
      "86",
      "ألفارد",
      "أوريون",
      "أفالون",
      "أفانزا",
      "أفينسيس",
      "BZ4X",
      "C-HR",
      "كامري",
      "سيلكا",
      "كوستر",
      "كورولا",
      "كورونا",
      "كريسيدا",
      "كراون",
      "إيكو",
      "إف جي كروزر",
      "فورتشنر",
      "فرونت لاندر",
      "GR86",
      "جرانفيا",
      "هايس",
      "هايلاندر",
      "هيلكس",
      "آي كيو",
      "إنوفا",
      "لاند كروزر",
      "ليفين",
      "MR2",
      "ميراى",
      "بيك أب",
      "برادو",
      "بريفيا",
      "بريوس",
      "رايز",
      "راف 4",
      "روميونو",
      "راش",
      "سيون",
      "سيكويا",
      "سيينا",
      "سوبرا",
      "تاكوما",
      "تيرسل",
      "توندر",
      "أوربان كروزر",
      "فيليز",
      "فينزا",
      "فيتس",
      "ويغو",
      "إكس إيه",
      "ياريس",
      "زيلاس",
      "BZ3",
      "iA",
      "أخرى",
    ],
  },
  {
    label: "فولكس فاجن",
    value: "فولكس فاجن",
    enValue: "Volkswagen",
    models: [
      "الكل",
      "Arteon",
      "Atlas",
      "Beetle",
      "Bora",
      "Corrado",
      "Caddy",
      "Crafter",
      "E-Lavida",
      "EOS",
      "Eurovan",
      "GTI",
      "غولف",
      "ID.3",
      "ID.4",
      "ID.6",
      "ID.7",
      "جيتا",
      "Multivan",
      "فايتون",
      "بولو",
      "روتان",
      "سيروكو",
      "شاران",
      "T-Roc",
      "Tayron",
      "Teramont",
      "Tiguan",
      "توارك",
      "ترانسبورتر",
      "فينتو",
      "فيلوران",
      "آخرى",
    ],
  },
  {
    label: "فولفو",
    value: "فولفو",
    enValue: "Volvo",
    models: [
      "الكل",
      "C-Class",
      "C40",
      "S-Class",
      "S90",
      "V-Class",
      "V90",
      "XC40",
      "XC40 Recharge",
      "XC60",
      "XC70",
      "XC90",
      "آخرى",
    ],
  },
  {
    label: "Xiaomi",
    value: "Xiaomi",
    enValue: "Xiaomi",
    models: ["الكل"],
  },
  {
    label: "Zeekr",
    value: "Zeekr",
    enValue: "Zeekr",
    models: ["الكل", "001", "007", "009", "X", "آخرى"],
  },
];
